### ISSUE TITLE
Dark mode background color

### ISSUE THREAD

**Issue by heberjeur** [bmx666/android-appcachecleaner#10]
Hi,can you change the background or text color of extra search text?
![Screenshot_20220730-190810_AppCacheCleaner](https://user-images.githubusercontent.com/11852634/181936259-172f6e54-a3e7-4504-a86f-a0fc838405a6.jpg)

**Comment by bmx666** [comment]
Hi @heberjeur I already fix it here - https://github.com/bmx666/android-appcachecleaner/commit/d6f1f86f5bcc391eb1f44dffd638145f58e6513d
I want to include few more changes into new release v0.0.9

**Comment by bmx666** [comment]
Hi @heberjeur , check new release [v0.0.9](https://github.com/bmx666/android-appcachecleaner/releases/download/v0.0.9/app-release.apk)
