### ISSUE TITLE
Automatic scheduled cleaning

### ISSUE THREAD

**Issue by birykvlad** [bmx666/android-appcachecleaner#106]
Dear developer,

Is it possible in the future to implement scheduled cache flushing to minimize manual control?

**Comment by bmx666** [comment]
Hi @birykvlad need to check, because I never did it before and if it works with locked screen

**Comment by birykvlad** [comment]
Got it, thanks! It will be good if you note this question as a potential feature of the request

**Comment by bmx666** [comment]
Hi @birykvlad , unfortunately Accessibility service doesn't work with locked screen. I can suggest only alternative solution - #30
