### ISSUE TITLE
AppCacheCleaner does not clean cache of all selected apps

### ISSUE THREAD

**Issue by Massedil** [bmx666/android-appcachecleaner#108]
Hello and thanks for your app !

I experience an issue : when I try to clean the cache of my apps, some of the apps are not cleaned (2 apps out of 5 are not cleaned on one of my recorded screen videos).

I tried to put the "Maximum timeout per app" to 60s, but it is not fixing the problem. The app wait less than 60s and fails to purge cache for some apps.

I tried with the last 1.7.0 version from F-droid, but problem occurs since I first tried the app month ago.

I wanted to send you privately a link to a video for helping, but I didn't succeed to find an e-mail to contact you. Let me know if you are interested.

Phone : Samsung Galaxy S5 / Android 11 / LineageOS 18.1

**Comment by bmx666** [comment]
Hi @Massedil thanks for feedback!

You can attach short video directly on GitHub in comment, or upload videos on https://streamable.com

**Comment by Massedil** [comment]
Hi, thanks for your reply.

About the video, I prefer to not make it public here because there is potentially private informations (list of apps, notifications, home app, etc.), that is why I ask how to send it to you only, if it can be helpful.

**Comment by bmx666** [comment]
Hi @Massedil I can't share my personal email here due to privacy reason. You can create custom use list to include only these apps, start record screen, wait few seconds before press clear custom apps and after cache clean wait few seconds then stop recording. Before upload video cut it.

**Comment by Massedil** [comment]
Here you will see 2 videos and a screenshot of the appcachecleaner list before and after each video : 
https://drop.chapril.org/download/2b4b7c09c8859dde/#ZnQy5nmM5Lu4X6l2A_PqDA

**Comment by Massedil** [comment]
Hi ! @bmx666 and thanks for your reply !

> app will generate log file (no privacy, only app name) and attach it here

Will the debug app automatically upload the log file (I hope no !) or will I have the opportunity to get the log file, review it and post it here  (as I would like :)) ?

**Comment by bmx666** [comment]
Hi @Massedil these log file will be saved on your phone as text file.

**Comment by Massedil** [comment]
I have reproduced the problem with the debug apk, you will find here 2 screenshots and the log file :
https://drop.chapril.org/download/ffb1fb980fb660fb/#QNWPpUs3fLeZ17Z0DELECA

**Comment by bmx666** [comment]
Hi @Massedil, thanks for the log file, according to your log - the app can find the storage menu, it has the status "enabled" and the app did perform click on it, then the Accessibility service got a new UI update and the app found the "clean cache" button, but it was in the "disabled" state, even after the timeout, because your phone is still calculating cache... The UI didn't update the button's state to "enabled".

Found and click
```
D: found clean cache button
D: clean cache button is enabled
D: perform action click on clean cache button
```

In some cases Accessibility service didn't get Enabled status even after timeout:
```
D: found clean cache button
```

Please increase the timeout in settings to 120 seconds because your internal memory on your phone is slow or/and degraded so cache calculation can take much longer than on newest phones with fast memory.

**Comment by bmx666** [comment]
Hi @Massedil sorry, my mistake, these is no timeout if button has state "Disabled", I will update algorithm to wait a few seconds before skip and go to the next app.

**Comment by bmx666** [comment]
Hi @Massedil  could you please verify this debug version [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11444990/app-debug.apk.zip) ?

Anyway, please attach log files here if it will be OK or the same.

**Comment by Massedil** [comment]
Hi @bmx666, something is not working fine with the last debug apk. During the cleaning phase, the app wait infinitely on some "Parameter app screen" (I had to my self click on the return arrow to leave the screen). The new floating icon stay displayed after the comeback to appcachecleaner, the log file is empty (0 octet), and there is an Application Not Responding screen about appcachecleaner. So I killed it. Tried to relaunch a cleaning and I recorded a video this time : the cleaning does not occurs at all : coming back to main screen immediately.

**Comment by Massedil** [comment]
Second record : https://drop.chapril.org/download/71b3a764d13adf4f/#A7-JnEJnzaOO7HT9vucLNA

**Comment by bmx666** [comment]
Hmm @Massedil did you reboot smartphone after installing the latest APK?
Sometimes Android has a problem with Accessibility service.

**Comment by Massedil** [comment]
After a full reboot of my phone : https://drop.chapril.org/download/43f3ce727b57c799/#0u4SamMVBjgQ_C0ouaZ7Rw

There is a log this time, but the clean does not work anymore. We can see on the video that appcachecleaner is waiting a long time while the buttons are already available to clear the cache. Then it immediately go the log file record, without cleaning the first app of the list.

**Comment by bmx666** [comment]
Hi @Massedil thanks for video and log, seems button doesn't notify Accessibility about updated state from Disable to Enable. I will try to refresh view element and request state again and I will add new debug version later.

**Comment by bmx666** [comment]
Hi @Massedil could you please check if new debug version works fine?

[app-debug-v2.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11481930/app-debug-v2.apk.zip)

**Comment by Massedil** [comment]
Hi, I have tested your last debug apk.

The cleaning is much better but not perfect ! I had cleaned mostly all my apps by the first try of cleaning.

There is still strange waiting times visually, like if the app do nothing while the screen is available. 

Sometimes, I have the impression that the app do something in the background not corresponding to the parameters screen I see. For example, I cannot clearly see for each app all the steps : 1. parameters of the app, 2. storage, 3. button to clear is now available. 4. click on the clear button.

For the second try of cleaning, I recorded it. 

In the video you will see my 2nd, 3rd and 4th try :
- 2nd try (appcachecleaner-log6.txt, 00:00 -> 00:40) : 
    - the first selected app never appears on screen and is not cleaned at the end
    - the second selected app appears on screen and is correctly cleared at the end
    - the third selected app appears on screen, and cache is correctly cleared at the end, but you can see that there is a long wait after cache cleaning (4 seconds ?) and recording of the debug file.
    - The floating icon does not indicate the good app list number (it shows 1/3 on the app n°2 and 2/3 on the app n°3)
- 3rd try (appcachecleaner-log7.txt, 00:40 -> 01:12) : 
    -  Nothing is cleared for the app
- 4th try (appcachecleaner-log8.txt, 01:12 -> end) : 
    -  Nothing is cleared for the app

https://drop.chapril.org/download/87043f197cbc7dd6/#psivr3uo8fJRX_IWfJoudQ

**Comment by bmx666** [comment]
Hi @Massedil thanks for log files.

I found one issue related to "wait" enable status, because there is no feedback, only way is figure out if fields has label "calculation..." otherwise process just stuck, because for other apps "Clear cache" button can be never enabled and it cause long hang.

Issue related to F-Droid - there is no event from Accessibility service, nothing happens... looks like there is an issue in LineageOS firmware for your phone.

Anyway I will pause investigation, because too much specific stuff and I will focus only on status from "Disable" to "Enable" during cache calculation... other issues are out of my scope.

**Comment by Massedil** [comment]
Hi !

> I found one issue related to "wait" enable status, because there is no feedback, only way is figure out if fields has label "calculation..." otherwise process just stuck, because for other apps "Clear cache" button can be never enabled and it cause long hang.

Ok.

> Issue related to F-Droid - there is no event from Accessibility service, nothing happens... looks like there is an issue in LineageOS firmware for your phone.

If you want, I can open a ticket on the LineageOS issue tracker if you let me better understand the "firmware problem".

> Anyway I will pause investigation, because too much specific stuff and I will focus only on status from "Disable" to "Enable" during cache calculation... other issues are out of my scope.

Ok, let me know if you want me to test a new apk. 

Thanks ! :)

**Comment by marcoXbresciani** [comment]
Same trouble for me, on Motorola G31, Android 12.

Attaching logs done with debug v2 app above. Second one Ive specifice the cache button even if it's as default, but still no all caches deleted. Tineout at 60 seconds.

[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/12319083/appcachecleaner-log.txt)

[appcachecleaner-log2.txt](https://github.com/bmx666/android-appcachecleaner/files/12319084/appcachecleaner-log2.txt)

**Comment by bmx666** [comment]
> Same trouble for me, on Motorola G31, Android 12.
> 
> Attaching logs done with debug v2 app above. Second one I've specified the cache button label even if it's as default, but still not all caches deleted. Tineout at 60 seconds.

Hi @marcoXbresciani thanks for logs, I checked it. Cache Cleaner do perform click on "Storage" and it returns OK, but Accessibility returns the same UI View Tree that was before. Looks like something specific related to your behavior.
Is it official Android 12 or custom ROM?

**Comment by marcoXbresciani** [comment]
It's an official Android 12 update from Motorola. Another (strange?) thing is that I have to set accessibility permissions everytime I reopen the app. SuperFreezZ from FDroid as well can keep those.

**Comment by bmx666** [comment]
@marcoXbresciani do you close app by clicking "close app" button? "stop accessibility service" button? OR when just restore app from background?

**Comment by marcoXbresciani** [comment]
I'm closing the app just like the others, swiping it from top to bottom.
Then every evening (sometimes even during the day) I use above SuperFreezZ to froze all pending apps.
When freezing it, I have to restore permissions.
(If I freeze SuoerFreezZ itself, I don't need to restore its accessibility permissions, at least recently: many months/versions ago, sometimes it happened)

**Comment by bmx666** [comment]
@marcoXbresciani maybe it's related to battery optimization and restrictions? Background services optimization to free unused app?

**Comment by bmx666** [comment]
> Tried to remove battery optimization, no luck. No background limitations except default. No other special things, as far as I know. Same results: some apps are cleaned, sometimes it doesn't clean a thing, ...

@marcoXbresciani sorry for misunderstanding, battery optimization was related to Accessibility service. Does it stop after swiping it out?

**Comment by marcoXbresciani** [comment]
Oh, no no, it doesn't.
If I don't freeze the app (with SuperFreezZ), it keeps the Accessibility permission.

**Comment by marcoXbresciani** [comment]
Could it be useful to slow down the second click? Maybe on my device the cache page takes a few more time to appear... don't know.

**Comment by bmx666** [comment]
> Could it be useful to slow down the second click? Maybe on my device the cache page takes a few more time to appear... don't know.

It was mentioned earlier - https://github.com/bmx666/android-appcachecleaner/issues/108#issuecomment-1553288849

**Comment by bmx666** [comment]
Hi @Massedil I made a small improvements to clean cache. Could you please check it and say if it helps or not?

[app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13196952/app-debug.apk.zip)
Rename back into app-debug.apk, reboot device and try that debug version.

**Comment by bmx666** [comment]
Hi @RichardBeisser and @Massedil 
I added timeout for Clear Cache button in option. Could you please test and verify it?

Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13198981/app-debug.apk.zip)

**Comment by RichardBeisser** [comment]
> Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13198981/app-debug.apk.zip)

Thanks for fast reply.
I tested it.
I seems that your cleaner not wait fixed the set seconds until it press the button "clear cache".
for my example with KODI with 241MB cache size, the button is now active, but it seems that cache cleaner doesnt press the button.
KODI still appears in each further run.

2 Log-Files attached again.
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13199237/appcachecleaner-log.1.txt)
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13199238/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
@RichardBeisser, thanks I will do small update later and you can test it again.

**Comment by bmx666** [comment]
Hi @RichardBeisser , could you please check this debug version?

Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13199438/app-debug.apk.zip)

The app monitors the enabled state of the 'Clear Cache' button. If it is enabled, the app performs a click on it. Otherwise, the app sends a request to the Accessibility Service to update the view element and check the 'Enabled' state again without any feedback. This request happens every 250 milliseconds (4 times per second). If the 'Clear Cache' button becomes enabled during any of these checks, the app performs a click. If the Accessibility Service returns an error, the entire cache cleaning process is interrupted due to the Accessibility Service being in an inconsistent state.

P.S. I don't want to make simple things more complicated, hard to maintain.

**Comment by Massedil** [comment]
Hello and thanks for trying again to solve this issue.

> Hi @RichardBeisser and @Massedil I added option in Setting to set max wait timeout for Clear Cache button. Could you please test and verify it?
> 
> Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13198981/app-debug.apk.zip)
> 
> P.S. In the next release I have plans to create an optional list to set specific timeout for specific apps, so other apps will ignore timeout Clear Cache button.

I tried the debug version from this post.

Here are logs and screenshots : 
https://drop.chapril.org/download/767392d9dfc35084/#CJDsQJWEz38Q5MafNPMiyA

You can see that EasyRSS is not cleared at the end of the procedure.

**Comment by bmx666** [comment]
Hi @Massedil thanks for the test, attached version had some issues.

Could you please try the latest debug from previous comment? -> https://github.com/bmx666/android-appcachecleaner/issues/108#issuecomment-1784255962

And also please set Max timeout for Clear Cache button in the Settings, at least 1 second, but 2s is better.

**Comment by RichardBeisser** [comment]
some new logs for you
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13209732/appcachecleaner-log.1.txt)
[appcachecleaner-log (2).txt](https://github.com/bmx666/android-appcachecleaner/files/13209733/appcachecleaner-log.2.txt)
[appcachecleaner-log (3).txt](https://github.com/bmx666/android-appcachecleaner/files/13209734/appcachecleaner-log.3.txt)
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13209735/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
Hi @RichardBeisser did you set max timeout to wait Clear Cache button in Settings at least 2-3 seconds?
I didn't see any delays in logs, because if timeout is 0 then app skip wait loop.

Log must contain a line in case of any delay:
===>>> findClearCacheButton: refresh BEGIN <<<===

**Comment by RichardBeisser** [comment]
> did you set max timeout to wait Clear Cache button in Settings at least 2-3 seconds?

Yes, I read what you have written to Massedil.
I set it to 3 seconds. When you look how you app is working, it realy waits the this time. 
This happens to all apps which you have selected for cache deleting.

**Comment by RichardBeisser** [comment]
I found the problem. It was my fault. I never deinstalled an earlier debug-version. I installed every apk from you as "update".
New logs attached (without reboot after installation)
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13210961/appcachecleaner-log.1.txt)
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13210962/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
> I found the problem. It was my fault. I never deinstalled an earlier debug-version. I installed every apk from you as "update". New logs attached (without reboot after installation) [appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13210961/appcachecleaner-log.1.txt) [appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13210962/appcachecleaner-log.txt)

No worries, does it work now? According your logs it waits and then press

> D: ===>>> doCacheClean BEGIN <<<===
> D: ===>>> findClearCacheButton: tries = 16 <<<===
> D: ===>>> findClearCacheButton: loop: tries left = 15 <<<===
> D: ===>>> findClearCacheButton: loop: refresh, BEGIN <<<===
> D: ===>>> findClearCacheButton: loop: refresh, END <<<===
> D: ===>>> findClearCacheButton: loop: tries left = 14 <<<===
> D: ===>>> findClearCacheButton: loop: refresh, BEGIN <<<===
> D: ===>>> findClearCacheButton: loop: refresh, END <<<===
> D: ===>>> findClearCacheButton: loop: tries left = 13 <<<===
> D: ===>>> findClearCacheButton: loop: is enabled, BREAK <<<===
> D: ===>>> findClearCacheButton: loop: is clickable, BREAK <<<===
> D: found clean cache button
> D: clean cache button is enabled
> D: perform action click on clean cache button

**Comment by bmx666** [comment]
> @RichardBeisser I made a new debug version with more debug information and it also check if button not just enabled but also clickable. Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13210212/app-debug.apk.zip)
> 
> P.S. Please reboot your phone after installation. I noticed in the log that there are duplicates which might have been caused by an old debug service that's still running.

Hi @RichardBeisser and @Massedil , could you please confirm that debug version fixes the current issue?
I want to make a new release.

**Comment by RichardBeisser** [comment]
from my point of view, you can make a new release. I used your debug-version several times after KODI had a big cache, and it could delete cache every time.

I dont know the exact problem of Massedil. I only read the subject of the thread.
I also made the notice that your cache cleaner doesnt clean the cache of all selected apps at the first run. You have to use several runs before all caches are cleaned.
Because I had this thing at the moment, I attached 2 logs, from first run and the second one.
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13226231/appcachecleaner-log.1.txt)
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13226232/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
Hi @RichardBeisser in the first log you get Accessibility service collision: old one doesn't stop properly and lost connection with app, and it's not possible to kill it anymore. And everything goes wrong. But it happens only in debug version, after installing release and uninstalling debug it should be fine.

> D: clearCacheApp: package name = org.xbmc.kodi
> D: clearCacheApp: open AppInfo
> D: [Service] sendAppInfo: package name = org.xbmc.kodi
> D: [Activity] CleanCacheAppInfo: package name = org.xbmc.kodi
> D: clearCacheApp: package name = com.aurora.store
> D: clearCacheApp: open AppInfo
> D: [Service] sendAppInfo: package name = com.aurora.store
> D: [Activity] CleanCacheAppInfo: package name = com.aurora.store
>

**Comment by Massedil** [comment]
Hello,

With the latest debug apk, in app settings, I have set :
- `Max. timeout per app - 30s` to `30` (default)
- `Max timeout to wait Clear Cache but..` to `29` instead of the default value `0`

It seems to solve the original problem, all apps are cleared now (or I haven't succeed to reproduce the problem) !

Here is a log :
https://drop.chapril.org/download/6b94d5799cf66e37/#JfzZDdY9OmlpgWz9T0fgVQ

Thanks !

**Comment by Massedil** [comment]
Sorry, the bug is still here. I finally succeed to reproduce the problem.

In the attached logs, the 1st of 5 apps "Galerie" is not cleared after the process.

It is like if the 2nd app "clear cache process" is launched before the first one is finished. I don't know if you can see it in the logs.

https://drop.chapril.org/download/a94ec8d6e6a236be/#xePJDOe3uUmfFr4FyOyKBw

**Comment by bmx666** [comment]
Hi @Massedil you had the same behavior as @RichardBeisser had early -> https://github.com/bmx666/android-appcachecleaner/issues/108#issuecomment-1788788668

> D: clearCacheApp: package name = com.simplemobiletools.gallery.pro
> D: clearCacheApp: package name = com.simplemobiletools.gallery.pro
> D: clearCacheApp: open AppInfo
> D: clearCacheApp: open AppInfo
> D: [Service] sendAppInfo: package name = com.simplemobiletools.gallery.pro
> D: [Service] sendAppInfo: package name = com.simplemobiletools.gallery.pro
> D: [Activity] CleanCacheAppInfo: package name = com.simplemobiletools.gallery.pro
> D: [Activity] CleanCacheAppInfo: package name = com.simplemobiletools.gallery.pro
> D: clearCacheApp: package name = us.spotco.maps
> D: clearCacheApp: package name = us.spotco.maps
> D: clearCacheApp: open AppInfo
> D: clearCacheApp: open AppInfo
> D: [Service] sendAppInfo: package name = us.spotco.maps
> D: [Service] sendAppInfo: package name = us.spotco.maps
> D: [Activity] CleanCacheAppInfo: package name = us.spotco.maps
> D: [Activity] CleanCacheAppInfo: package name = us.spotco.maps
> D: ===>>> TREE BEGIN <<<===
> D: ===>>> TREE BEGIN <<<===

I will close this issue and create a new release.

**Comment by marcoXbresciani** [comment]
A few runs, with very latest dehug verdion.
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13232136/appcachecleaner-log.txt)
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13232137/appcachecleaner-log.1.txt)
[appcachecleaner-log (2).txt](https://github.com/bmx666/android-appcachecleaner/files/13232138/appcachecleaner-log.2.txt)
[appcachecleaner-log (3).txt](https://github.com/bmx666/android-appcachecleaner/files/13232139/appcachecleaner-log.3.txt)
[appcachecleaner-log (4).txt](https://github.com/bmx666/android-appcachecleaner/files/13232140/appcachecleaner-log.4.txt)
[appcachecleaner-log (5).txt](https://github.com/bmx666/android-appcachecleaner/files/13232141/appcachecleaner-log.5.txt)

**Comment by bmx666** [comment]
> A few runs, with very latest dehug verdion. [appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13232136/appcachecleaner-log.txt) [appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/13232137/appcachecleaner-log.1.txt) [appcachecleaner-log (2).txt](https://github.com/bmx666/android-appcachecleaner/files/13232138/appcachecleaner-log.2.txt) [appcachecleaner-log (3).txt](https://github.com/bmx666/android-appcachecleaner/files/13232139/appcachecleaner-log.3.txt) [appcachecleaner-log (4).txt](https://github.com/bmx666/android-appcachecleaner/files/13232140/appcachecleaner-log.4.txt) [appcachecleaner-log (5).txt](https://github.com/bmx666/android-appcachecleaner/files/13232141/appcachecleaner-log.5.txt)

Hi @marcoXbresciani from you log you had the same error as @Massedil and @RichardBeisser had before, please try the latest release version and uninstall debug version.
