### ISSUE TITLE
Total cache size

### ISSUE THREAD

**Issue by heberjeur** [bmx666/android-appcachecleaner#11]
Hi @bmx666 can you add total cache size to know before/after app cleaning

**Comment by bmx666** [comment]
Hi @heberjeur , check release [v0.1.2](https://github.com/bmx666/android-appcachecleaner/releases/tag/v0.1.2). Is that what you wanted?

**Comment by heberjeur** [comment]
> Hi @heberjeur , check release [v0.1.2](https://github.com/bmx666/android-appcachecleaner/releases/tag/v0.1.2). Is that what you wanted?

Yes, thank you 😊
