### ISSUE TITLE
App isn't working

### ISSUE THREAD

**Issue by E0697** [bmx666/android-appcachecleaner#110]
The app doesn't work on RealmeUI3.0
Sometimes it gets to the app info page, sometimes to the storage details page, and sometimes nowhere. But it never clears the cache.

**Comment by bmx666** [comment]
Hi @E0697 , could you please install the debug version 1.7.0 after clear cache process app will generate log file (no privacy, only app name) and attach it here.

Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11433813/app-debug.apk.zip)

**Comment by E0697** [comment]
Here's the [log](https://pixeldrain.com/u/BViFGx3y) file.

**Comment by bmx666** [comment]
Hi @E0697 thanks for log, according your file app found Storage button, clicked it, but nothing after, no event from Accessibility service and clean process was finished.
Can you attach short screen record video of it with log?

**Comment by E0697** [comment]
Sure thing. I remember in the non-debug version it used to get to the storage info screen but not tap the the clear cache button.
https://github.com/bmx666/android-appcachecleaner/assets/66939100/b41ae47f-eb9d-499b-b0de-7d062f72e148

**Comment by Gamefire238** [comment]
The case is the same as mine, only with a different pattern

https://github.com/bmx666/android-appcachecleaner/assets/78879425/a589eeb3-50ac-4982-b9c4-0197657a4b1f

It takes two clicks to clear cache on my device
