### ISSUE TITLE
In dark mode, progress to clear cache is not visible

### ISSUE THREAD

**Issue by franco27** [bmx666/android-appcachecleaner#113]
Hello

When the Android system goes into dark mode, we no longer see below your icon, 1/8, 2/8, 3/8, ...

![IMG_20230529_224300.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/e988c048-aeb6-4d8b-83e8-de13e1a9297c)

![Screenshot_2023-05-29-22-35-11-159_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/3d05bf8c-556f-43db-89f6-b6c9b161b9dc)

**Comment by bmx666** [comment]
Hi @franco27 , is it the same behavior if you force set Dark mode in the Settings of Cache Cleaner?

**Comment by franco27** [comment]
For the 1st message, it's the Android system going into dark mode (I didn't activate Cache Cleaner's dark mode in the settings).
However, I found after switching or enabling the Android system dark mode that your app colors changed. (A dark color )

To answer your question, I have enabled dark mode, when android system dark mode is enabled and there is the same problem. I am attaching a screenshot, as you can see.

![Screenshot_2023-06-03-21-50-29-513_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/d7a76e3f-6fff-4f91-a7f2-470402babe76)

**Comment by bmx666** [comment]
Hi @franco27 thanks for check, seems UI settings for Accessibility overview in your case overrides somehow, even it's set as white background with black color font.

```
    <TextView
        android:id="@+id/overlayText"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textAlignment="center"
        android:textColor="@color/black"
        android:background="@android:color/white" />
```

**Comment by bmx666** [comment]
I will add option to check if force dark mode was set, then use black background with white color font. I hope it will help.
I will attach APK here, so you can verify it.

**Comment by franco27** [comment]
THANKS. It may also be because Xiaomi does not do like everyone else, with its Android overlay.

No worries, to test the apk

**Comment by bmx666** [comment]
Hi @franco27, yes it's my "favorite" smartphone company! No rules, no compatibilities!

Could you verify this version ->  [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11646629/app-debug.apk.zip)
Just remove ".zip" and install APK. I will wait for your feedback.

**Comment by franco27** [comment]
Yes, me, this is the first Xiaomi phone.

I just tried with APK, Android system has dark mode enabled. Your application is in dark mode, but in the settings the dark mode is disabled.
I still don't see the progress numbers. See the screenshots.

I'll give it a second try, this time turning on dark mode in the app. See if there is a change in behavior.

![Screenshot_2023-06-04-23-38-53-656_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/473209cd-4d5c-4317-bc7a-30946c518d66)

![Screenshot_2023-06-04-23-38-49-226_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/10c0009c-60df-451c-a810-11c7404c4474)

**Comment by franco27** [comment]
The second try is the same. See screenshot

![IMG_20230604_235431.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/a69229fc-c92d-4437-b7da-c76b381cfe8d)

![Screenshot_2023-06-04-23-55-52-471_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/3d53c04b-31b1-4c7b-ba0d-ed24ca79c987)

![Screenshot_2023-06-04-23-56-04-617_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/9cfdeeb6-f7a0-46bb-81e4-6e69d1249e42)

**Comment by bmx666** [comment]
Hi @franco27 thanks a lot, seems it doesn't work well, I need to find another way how to do it.

**Comment by bmx666** [comment]
Looks like Xiaomi ignores android:textColor="@color/black"
I will make two layouts for light and dark mode.

**Comment by bmx666** [comment]
Hi @franco27 , could you please verify a new debug version?
[app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11657899/app-debug.apk.zip)

**Comment by franco27** [comment]
Hello
I tested with the new version of debug . And always the same. See the screenshot.
Android system enabled dark mode and I set dark theme in app.

![Screenshot_2023-06-06-21-32-25-960_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/13260215-1007-437b-8b14-3b3173dc3510)

**Comment by bmx666** [comment]
HI @franco27 , strange, but to be clear and avoid misbehavior, but did you test "Clean Cache Debug" that generate logs after cache clean? Because "Clean Cache" is release version and it separated from a debug app. Both apps could be installed on a smartphone.
If you run 100% debug version, then it's really weird Xaomi behavior and I can't do anything with it.

**Comment by franco27** [comment]
Yes I am running the Debug version and yes the other version is still installed alongside.
For testing, I only use the debug version.

**Comment by franco27** [comment]
https://drive.google.com/file/d/1HD2kaf1U9dXxJtNiWzemlIVdxGh0Xt22/view?usp=drivesdk

**Comment by bmx666** [comment]
Hi @franco27 thanks for clarification. Then these is should be another way for Xiaomi, even with dark mode force background still has white color and white don't color 😭
Meanwhile I will push night mode fix for other smartphones and I will try to find a way for Xiaomi.

**Comment by franco27** [comment]
However you did not tell me to activate this option, I just discovered it. See screenshot.
Nevertheless, it is always the same. The progress display is invisible.

A second thing, since I enabled this option, no cleaning is done. I mean application caches are not cleared with this option enabled.

![IMG_20230607_213911.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/f1aa946e-524b-4129-ad4d-591dc47f7f39)

**Comment by franco27** [comment]
Here is the log file

https://drive.google.com/file/d/1-hKlUPLNBy55TqW3f13YJbt0oCM_UNGC/view?usp=drivesdk

**Comment by bmx666** [comment]
@franco27  this option is related to issue #65, if you doesn't have a problem with Default scenario, then please don't use special Xiaomi scenario.

**Comment by franco27** [comment]
> @franco27  this option is related to issue #65, if you doesn't have a problem with Default scenario, then please don't use special Xiaomi scenario.
> 
> > Xiaomi smartphones with specific regional MIUI firmware must use the different clear cache scenario

You have implemented this option with this issue
I thought you created it for the display issue with dark mode

**Comment by franco27** [comment]
Me, with the default option, the cleaning is done correctly.

It's just that I don't see the progress numbers with the Android system and / or app dark modes.

**Comment by franco27** [comment]
It seems Xiaomi is the problem.
I left the setting, dark theme for your app. And Android system, was in clear mode.
Here is a screenshot.

![Screenshot_2023-06-08-14-47-46-312_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/0b4ab598-66e9-438f-98a5-c7815b05965a)

**Comment by bmx666** [comment]
Hi @franco27 thanks for tests. So now the behavior:
1. Light mode app + Xiaomi Light mode - white background + black font
2. Force dark mode + Xiaomi Light mode - black background + white font
3. Dark mode + Xiaomi dark mode - white background + white font
4. Force Dark mode + Xiaomi dark mode - white background + white font
Now the major problem why Xiaomi sets white background in dark mode 🤔

**Comment by bmx666** [comment]
Could you test the solution here? Is it work for you?

https://en.gizchina.it/2021/04/xiaomi-miui-12-dark-mode-inverted-colors/

**Comment by bmx666** [comment]
Hi @franco27 I'll keep this bug open, but unfortunately I don't have time to investigate further.

**Comment by franco27** [comment]
Hello.
I read the article and I saw these extra options for the dark mode of the system.
there are two additional parameters that were enabled.
I disabled both of these parameters and re-tested your application.
Unfortunately, that doesn't change anything. Still the same behavior, I still don't see the numbers that indicate progress in cleaning. (for the test, dark mode was enabled in the application).

![IMG_20230610_010456.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/50e2d606-a696-4a68-bf71-8b12fe998854)

**Comment by bmx666** [comment]
Hur @franco27 I will try add option in the Settings then for Xiaomi force dark mode only, because this workaround breaks default behavior on other devices with dark mode.

**Comment by bmx666** [comment]
Hi @franco27 could you check this debug version in Xiaomi dark mode with and without "Dark mode" in the Settings? [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11726565/app-debug.apk.zip)

**Comment by franco27** [comment]
And good news 🥳
 You managed to correct and solve this problem.
I did both tests, both were successful.

The first with the dark theme disabled in the application, knowing that the Xiaomi Android system dark mode still enabled it (but the setting in the application is disabled).
The second, I activated the dark theme of the application and still the same result. 
I now see the progress numbers.
Obviously, the dark mode of the Android system for both tests was activated.

![Screenshot_2023-06-13-05-17-25-539_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/86fb9afa-c932-44e0-98a8-bfc51f7026d3)

![Screenshot_2023-06-13-05-17-42-909_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/17300997-d2e9-4bd6-8996-22489b056961)

**Comment by bmx666** [comment]
Hi @franco27 thanks for feedback. Could you please also verify that works in light mode, and light mode + dark mode in app?
I want to be sure that everything is good 😁

**Comment by franco27** [comment]
Previously,
Android System Dark Mode and App Dark Theme Enabled = Success
Android system dark mode and app dark theme disabled (but app is dark mode by system) = Success

Now I just did the tests.
It is a success the other two tests.

Each time, the Android system's clear mode is activated.
1st test, application dark theme disabled = success
2nd test, with activated dark theme of the application = success

That's another topic, but between every cleanup (even keeping the window open in the foreground and doing a second cleanup directly after the first cleanup), I'm forced to force quit your app through Android settings, and before that, by your application button, forced to disable accessibility, otherwise the second cleaning does not work.

I give you the system information of my Xiaomi: Xiaomi Redmi 8,
Android Version 10 and
MIUI V12.5.2.0.QCNEUXM.

![Screenshot_2023-06-13-11-09-28-530_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/48165877-1a6f-4fd9-8feb-0afc3d2ad33f)

![Screenshot_2023-06-13-11-03-23-419_com.android.settings.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/e30eaf77-a296-48f4-8ada-d32cdc5c9832)

**Comment by franco27** [comment]
Also thank you for solving the problem.
 For the other problem, I will create another topic.
 As we don't generally do 2 cleanings at the same time, this problem is not too awkward. THANK YOU
