### ISSUE TITLE
Add an extra button for each app in the list to launch app info

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [bmx666/android-appcachecleaner#118]
Since there are many ui that isn't supported, and it'd take time, so how about adding a i button next to the app so users can directly access the app info page of the app so we can easily clear the cache, the thing is going through apps menu in settings and finding those apps is so slow (especially with my device) it takes like a min or 2 to load the page itself so it'd be a lifesaver to be able to access the app info page directly through this app, even though it's not automatic fo me!
Please add this.
Thanks!

**Comment by bmx666** [comment]
Hi @Black-StellarSpectrum, great idea, I will check it!

**Comment by bmx666** [comment]
Hi @Black-StellarSpectrum I tried to add extra button to list, but it's looks ugly especially on small screen devices, so I decided to add Click event that inform about **"Hold the app icon to launch "App Info"** and the Long Click will open **AppInfo**. Looks simple and much cleaner.

**Comment by gbdomubpkm** [comment]
nice @bmx666 ! 😉 😁

**Comment by Black-StellarSpectrum** [comment]
> Hi @Black-StellarSpectrum I tried to add extra button to list, but it looks ugly, especially on small screen devices, so I decided to add Click event that inform about **"Hold the app icon to launch "App Info"** and the Long Click will open **AppInfo**. Looks simple and much cleaner.

Thanks, received the update, it's so much better now, to go to app info directly, Thanks once again for implementing the feature!
