### ISSUE TITLE
  Application permissions window opens causing cleaning to stop 

### ISSUE THREAD

**Issue by franco27** [bmx666/android-appcachecleaner#121]
Hello

With version 180, problems to complete the cleaning
The process hangs and stops on the window of the authorization of the applications (of each application)

1 I select the applications
2 The cleaning begins
3 When the Android window, of the authorizations of the application    is displayed, it remains displayed
 And the process is blocked on this window

Before, the window with the application cache was displayed

**Comment by franco27** [comment]
When I press the " back"  button on the Android system, or the "back arrow"  on the app permissions window, the process continues and hangs again

**Comment by franco27** [comment]
I uninstalled this version and installed v173, I have the same problem

**Comment by bmx666** [comment]
Hi @franco27 it's really strange. Do you have the same issue on v1.7.2 before support of Android 14?

**Comment by franco27** [comment]
With version 1.7.2 I have no problem. 
I don't have this malfunction. (And previous versions)
I only have the windows with the cache displayed

**Comment by bmx666** [comment]
Hi @franco27 did you install v1.7.2 from F-Droid or manually? I found this issue can be related to Xiaomi, again 😞

**Comment by franco27** [comment]
I downloaded the APK from Github and installed it

**Comment by bmx666** [comment]
@franco27 could you please test this version? ->
[app-release-v1.8.0-api33.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11919846/app-release-v1.8.0-api33.apk.zip)
I removed Android 14 support and re-build it for Android 13 and below.

**Comment by franco27** [comment]
It seems that the problem is not related to Android 14.

I have the same problem, but it showed the permissions window to the fourth app for cleaning.

And on the fourth application, I got stuck on this window

![Screenshot_2023-06-30-22-06-54-525_com.google.android.permissioncontroller.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/f2cae5b4-e4e1-4813-87c4-84d44c262b6d)

**Comment by franco27** [comment]
On the fifth application, sorry

**Comment by bmx666** [comment]
@franco27 , could you please made and share a screenshot of App Info of this app?

**Comment by franco27** [comment]
What do you want to know ?
This application was already installed with version 1.7.2 and even before (And with previous versions )

![IMG_20230630_232137.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/b4da8587-ec59-4738-956d-276524aeddd9)


![IMG_20230630_232702.jpg](https://github.com/bmx666/android-appcachecleaner/assets/31793920/5cf0fae1-38e2-4815-affd-5467cbde8e64)

**Comment by bmx666** [comment]
Ah, sorry, now I see where is the problem, on Android 14 all additional information was removed about all elements including ID and Accessibility Serivce returns only info about type of widget and text, like TextView -> "Espace de stockage et cache", but before it was TextView -> "Espace de stockage et cache" -> "android:id/title". I can easily separate "Stockage" description from "Espace de stockage et cache" title. But due to a lot of compatibility app is looking for all possible variants: "Espace de stockage et cache" and "Stockage". And then during iterations, it stops on "Stockage" description as TextView -> ("Espace de stockage et cache" or "Stockage"), goes to parent title "Autorisations" and clicks on it.

**Comment by franco27** [comment]
Thank you for your explanations

 In any case, I confirm that the problem is solved with the new version
