### ISSUE TITLE
First: automatic cache cleaner cache cleaning

### ISSUE THREAD

**Issue by gbdomubpkm** [bmx666/android-appcachecleaner#123]
As you know, a list's cache cleaning process may not start for some reason you explained somewhere.

And as a workaround (I think) I made a discovery while testing to see if it had any effect.
I explain:
- I launch the cleaning of a personalized list for example, the process may blocks at startup.
- If the process blocks, i clean the cache cleaner cache first then I restart the cleaning of the personalized list and everything is fine !!

If you confirm what I said, shouldn't the cache cleaner cache be cleaned first automatically at the start of any list to avoid blocking?

**Comment by bmx666** [comment]
Hi @gbdomubpkm , unfortunately if you check issues #8 #108 #110  in such cases it's related to Android system itself. Sometimes Android doesn't return any feedback even after perform click, looks like event was lost. And during the 2nd clean it can work again. But if you have the same effect after reboot Android and it's reproducible every time than I can be a bug or extra workaround is required.

Long time ago I had plans to make pre-recorded clean process or editor for custom cache clean scenarios, but it requires a lot of effort to implement this. It's nice for some users, but I wanted to create sharable scenarios for everyone and for new users especially.

**Comment by gbdomubpkm** [comment]
You are right ! What I'm saying works by cleaning the cache cleaner cache first, but not going through your app indeed which can block by listing that single app.
I actually use the discreet-launcher (falzonv) / long press for settings / app info / storage and cache / clear cache.
So it's no use to you.
Unless you can implement a way/workaround that can clean the cache cleaner cache for sure faster than mine.

Close this open issue if you think so and thank you again for this fabulous app !

**Comment by bmx666** [comment]
Hi @gbdomubpkm , I added few days ago a long press action to open AppInfo, check #118 

As for workarounds, in Android 14 even less info can be requested and received, only Google TalkBack has many features because it whitelisted for Android and it could access private and restricted API. So I think in Android 15-16 my app will be useless if Google will follow this path 😁😵

**Comment by gbdomubpkm** [comment]
> Hi @gbdomubpkm , I added few days ago a long press action to open AppInfo, check #118
> 
> As for workarounds, in Android 14 even less info can be requested and received, only Google TalkBack has many features because it whitelisted for Android and it could access private and restricted API. So I think in Android 15-16 my app will be useless if Google will follow this path 😁😵

Hi @bmx666 I'm only on android 12 AOSP 😁
