### ISSUE TITLE
Cleaning interruption 

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [bmx666/android-appcachecleaner#124]
The app keeps getting hung up on cleaning. It's saying interrupted on screenshot editor. Are there permissions I should check? Version 1.7.2 works fine with no interruptions.

**Comment by bmx666** [comment]
Hi @KnightmareVIIVIIXC , v1.8.1 haven't delivered yet. Could you verify it https://github.com/bmx666/android-appcachecleaner/releases/tag/v1.8.1 ?

**Comment by KnightmareVIIVIIXC** [comment]
1.8.1 works. Thank you for the reply!

**Comment by bmx666** [comment]
duplicate #121
