### ISSUE TITLE
Critical problem

### ISSUE THREAD

**Issue by Lucky390163** [bmx666/android-appcachecleaner#126]
Bro, android has restricted accessibility allow and i can allow for your app because it is not available for your app.It won't shows allow restricted access

**Comment by bmx666** [comment]
Hi @Lucky390163 , could you please provide more detail about that issue?

Is the problem related to the Warning in the README?

> Since Android 13 Accessibility APIs is restricted for 3rd party apps, the solution can be found [here](https://support.google.com/android/answer/12623953) at the paragraph Allow restricted settings.

Also, Android 13 received an update that prevents opening AppInfo from the app itself to enable accessibility, it's only possible if user do it from App list or Launcher -> App Info -> Enable Accessibility.

**Comment by Lucky390163** [comment]
It is fixed bro

**Comment by bmx666** [comment]
Hi @Lucky390163 I didn't get, fixed what? This issue or what?

**Comment by Lucky390163** [comment]
It was restricted by the system, android 13, not your app, so your app is working well.

Don't worrying all fine.

**Comment by bmx666** [comment]
Ok, good
