### ISSUE TITLE
Problem deleting cache of KODI / Apps with very big cache

### ISSUE THREAD

**Issue by RichardBeisser** [bmx666/android-appcachecleaner#131]
Hello,

i noticed that your Cache Cleaner seems to have a problem to delete Cache of App KODI.
My device: lenovo TB-X505F
ROM: https://sourceforge.net/projects/andyyan-gsi/files/lineage-20-td/lineage-20.0-20231017-UNOFFICIAL-arm64_bgN.img.xz/download

Perhaps this is because of very large cache is used.

I am a little bit confused, because when you click manually in  app seetings, you can delete cache without any problems.

You can start new runs as much as you want, always the same

![cleanerKODI](https://github.com/bmx666/android-appcachecleaner/assets/47367173/6d4f5321-f426-47f6-8b7d-e73c057be518)

![Screenshot_20231022-192743_Einstellungen](https://github.com/bmx666/android-appcachecleaner/assets/47367173/2c881575-8dac-4f85-bfc1-4b08d0642ae1)

**Comment by bmx666** [comment]
Hi @RichardBeisser could you try debug version with small modification and attach generated log here, I will analyze it.

[app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13196952/app-debug.apk.zip)
Rename back into app-debug.apk, reboot device and try that debug version.

**Comment by RichardBeisser** [comment]
> Hi @RichardBeisser could you try debug version with small modification and attach generated log here, I will analyze it.

sure, I attached 2 log files, one from first run, the second file is for eacht run after first run.

When you look how your app is working, it seems that your app doesnt wait enough time until button "clear cache" appears.
When you do it manually, you have to wait 1-2 seconds until button comes active.
![Screenshot_20231029-171700_Settings](https://github.com/bmx666/android-appcachecleaner/assets/47367173/e1c93807-92b4-42b0-9bb4-77d4467d5a18)

[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13198594/appcachecleaner-log.txt)
[appcachecleaner-log2.txt](https://github.com/bmx666/android-appcachecleaner/files/13198595/appcachecleaner-log2.txt)

**Comment by bmx666** [comment]
Hi @RichardBeisser,

It seems you have a similar issue to the one I mentioned in this comment: https://github.com/bmx666/android-appcachecleaner/issues/108#issuecomment-1553288849. I will mark your issue as a duplicate. Additionally, I'm considering redesigning the Cache Clean Algorithm to include an optional timeout. This will always wait the "Clean Cache" button, even if it should be disabled (0 size cache).
