### ISSUE TITLE
Vanilla Music hangs

### ISSUE THREAD

**Issue by M1Aston** [bmx666/android-appcachecleaner#134]
While cleaning user apps, Cache Cleaner needs two attempts to clean the cache of Vanilla Music player. The first time it "hangs".
The screenshot shows where it stops in the cleaning process.

![vanilla](https://github.com/bmx666/android-appcachecleaner/assets/43113612/d49276e8-c592-4f19-8698-9e559a624cf4)

**Comment by bmx666** [comment]
Hi @M1Aston could you please share more information about your phone? Android version, model, custom ROM?

Also please install debug version of the current version, (run only 2-3 apps, normal and problematic one) then apps will generate a log file. Please attach it here.

Remove zip extension and install apk file -> [app-debug.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13210212/app-debug.apk.zip)

**Comment by M1Aston** [comment]
I'll install that debug version and see what turns up.
My phone is quite old: Sony Xperia X running Android 8.

**Comment by M1Aston** [comment]
I hope this helps.
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13265647/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
Hi @M1Aston could you please check the same in English locale. Maybe these is something wrong with translation 🤔

**Comment by M1Aston** [comment]
What do you mean in English?

**Comment by bmx666** [comment]
> What do you mean in English?

Please set English as the default language in Settings, because your log file contains translations for the Dutch locale.

I want to compare original Android English strings which Google sets into Settings (Storage & cache, Clear cache).

> Many companies or Android ROMs add or change default Android UI, including Settings. This can cause an issue because the Cache Cleaner app is looking for specific text and if it doesn't match, the app does nothing.

I also found that in a few locales, different English terms (such as "Storage" and "Memory") are translated into the same word, "Stockage" in French and "Память" in Russian, respectively.

The app doesn't recognize the difference and selects the first option, but sometimes this is incorrect.

**Comment by M1Aston** [comment]
I did one run in English. Perhaps it's too soon to draw any conclusions, but it did work normally this time. Here is the log file, I hope it's useful.
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13294858/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
Hi @M1Aston I didn't see any issue. Log is ok.
Do you have it randomly?

**Comment by bmx666** [comment]
Hi @M1Aston again, do you have this kind of issue when using non-English System Locale?

**Comment by M1Aston** [comment]
Yes, the default language is Dutch.
I have done after changing the default language to English and so far there were no problems, i.e. cleaning worked normally without interruption\hanging.
