### ISSUE TITLE
Not clearing cache 

### ISSUE THREAD

**Issue by ADIT011007** [bmx666/android-appcachecleaner#141]
Device info : Redmi note 8 pro, Miui os . The app does not clear cache insted it just navigates to settings of all apps selected. To clear cache on this device : go to the app setting then then press clear data button on bottom and click on clear cache then click ok . That's it . I hope this helps you 

Regards ☺️

**Comment by bmx666** [comment]
Hi @ADIT011007, did you try to set different scenario in Settings for Xiaomi MIUI?

**Comment by ADIT011007** [comment]
Ok so i didn't know about that setting . But after selecting that scenario for xiaomi Miui . The all stopped working. Whever i selected apps and clicked the clear button it suddenly goes Back to the main menu where we have to select system apps or all apps . It not starting it goes back to main menu like ur crashed

**Comment by bmx666** [comment]
Hi @ADIT011007 , thank a lot for your feedback.
Ok, then it doesn't work too.
Could you please return back to Settings -> Scenario -> Default.

Try to set English as System language in your phone and repeat again.

In case of it doesn't work and because I don't have  any Redmi Note 8 Pro, Android FW version could be also locale depending, I would like to get at least few screenshots from you (you can attach here):
1. AppInfo of any app
2. Screen where button Clear Cache.

Please attach only 2 screenshots, no need more and set English as System language for your device

**Comment by ADIT011007** [comment]
link to see the app information page : https://ibb.co/3r0JxLv

First way to clear cache : https://ibb.co/yPKBTyx

Second way to clear cache : https://ibb.co/1mS2SHc

I have added text to the screens shots that will help you

**Comment by bmx666** [comment]
Hi @ADIT011007 you have the same behavior as here https://github.com/bmx666/android-appcachecleaner/issues/65

You should use Xiaomi MIUI scenario, but I need more information why it goes wrong.

>  i had to stop and start the accessibility service for teh app to work in default mode cuse every time i close app i need to restart the service cuse if I don't do that then it won't work and on the Android settings it would show service not working/ malfunction
Issue related to Accessibility service on Xiaomi/Redmi - https://github.com/bmx666/android-appcachecleaner/issues/52
Go to the Settings menu - "Show extra buttons" - enable to display "Start/Stop Accessibility Service" and "Close App" buttons

**Comment by bmx666** [comment]
@ADIT011007 could you please test debug version?

https://github.com/bmx666/android-appcachecleaner/releases/download/v1.8.6/app-release.apk

Debug version generates full trace of Accessibility behavior, so just select any 2-3 apps, start clean and after that app generate log file (no sensitive information, just package names).

**Comment by ADIT011007** [comment]
> @ADIT011007 could you please test debug version?
> 
> https://github.com/bmx666/android-appcachecleaner/releases/download/v1.8.6/app-release.apk
> 
> Debug version generates full trace of Accessibility behavior, so just select any 2-3 apps, start clean and after that app generate log file (no sensitive information, just package names).

Where can I get the generated log file ? I tried the debug version and its working as expected. So i think you are correct something is off with service

**Comment by bmx666** [comment]
Hi @ADIT011007 , my fault wrong link.

Debug version here - https://github.com/bmx666/android-appcachecleaner/releases/download/v1.8.6/app-debug.apk

Anyway, what kind of scenario did you set? Default or Xaomi MIUI?
If it works in your case, then you can close this issue.

**Comment by ADIT011007** [comment]
The apps seems to work the only problem is that once app is closed , I need to restart the accessibility service for the app to work as intended else it would crash and go to main menu ..is there any way to add a button to start the service once stopped ?

**Comment by bmx666** [comment]
Hi @ADIT011007

> is there any way to add a button to start the service once stopped ?

Yes, Settings -> Show extra buttons -> Start/Stop Accessibly service.

I will add extra notes in Help menu about that.

**Comment by bmx666** [comment]
I added an extra note in Help menu for the next version 1.8.7

**Comment by ADIT011007** [comment]
The stop button never changes to start button. It's stuck on stop and I don't think the stop service button is working

**Comment by bmx666** [comment]
Sorry, but I couldn't help with it, it's not a application issue. It's a Xiaomi smartphone issue. Accessibility service should stay alive according Android Compatibility tests, but Xiaomi doesn't pass it and doesn't follow compatibility standards.

1. Try to set battery optimization as unrestricted for Cache Cleaner
2. Try use "Close App"
3. Someone mentioned about accessibility permission in Xiaomi MIUI
4. Maybe another settings for Xiaomi, Redmi, MIUI

**Comment by bmx666** [comment]
There is a lot of issues on Xiaomi even with
[Google TalkBack](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback). I still don't know how Google gave access to Google Play these smartphones which couldn't even pass basic compatibility tests for Android and I should receive a lot of negative reviews because it's not an application fault.
