### ISSUE TITLE
android 14 - accessibility is greyed out

### ISSUE THREAD

**Issue by jonathanmc** [bmx666/android-appcachecleaner#148]
Pixel 6a with android 14 and the selection in the accessibility menu for the program is completely grayed out " for my safety" It says.

I'm submitting this because I promised to submit bug reports in the opening screen :)

**Comment by jonathanmc** [comment]
Well I solved my own problem and it's not a problem with this app. 

What you need to do is go into the apps list in Android. Find this program and click the three dots in the upper right which should give you an option called " allow restricted" or some such.

You can then go back to the accessibility menu and add this program to the list.

**Comment by bmx666** [comment]
Hi @jonathanmc , no one reads [README](https://github.com/bmx666/android-appcachecleaner#warning-%EF%B8%8F), right? 😆

**Comment by jonathanmc** [comment]
There's a reason games don't come with manuals anymore :)

**Comment by bmx666** [comment]
> There's a reason games don't come with manuals anymore :)

Google Play removes that restriction only if you download the app from Google Play.
I upload updates right after release, on F-Droid a new release could be published during 1-14 days, on Google Play it takes around 1-2 days after reviewing process.
