### ISSUE TITLE
[feature request] ability to clear app data

### ISSUE THREAD

**Issue by 77-77SP** [bmx666/android-appcachecleaner#155]
I would like to know if it is possible to not only to clear app cache, but to clear app data too. So the app would not have **any** user data.

I tried changing the **Clear cache**  option from the **Add extra search text** to "Clear storage" so it would clear both data&cache, but it didn't work.

Thank you for your hard work developing this amazing app!

**Comment by bmx666** [comment]
Hi @77-77SP ,
Yes, it's possible, but unfortunately according Google Policy removing user data is prohibited and the app will be removed immediately from Google Play.

It could be implemented for F-Droid only.

**Comment by 77-77SP** [comment]
It would be awesome if it could be implemented in the F-Droid version of the app. If it wont be a hassle to you of course.

I think your app is best cache cleaner app for android. It's FOSS, doens't have unnecessary permissions like other apps and has a custom list ability. Having it able to clear app storage would be awesome.

Other feature request I would like to propose is the ability to quickly launch a custom clean. For example, having a quick tile for every list, which upon clicking would trigger the cleaning proccess automaticly. Or having a custom icon for every custom list I have on the launcher, which upon clicking would start the cleaning proccess. 

I know it might be too much to request for. I appreciate your hard work and time. I will keep using your amazing app either way.

**Comment by bmx666** [comment]
Hi @77-77SP about that

> Other feature request I would like to propose is the ability to quickly launch a custom clean. For example, having a quick tile for every list, which upon clicking would trigger the cleaning proccess automaticly. Or having a custom icon for every custom list I have on the launcher, which upon clicking would start the cleaning proccess.

I tried to start Accessibility service from tile, but for some reason Android context from tile has difference from Activity context. And it behaves strange. Also tile context doesn't work well with custom dialogs. So I decided just open activity directly without pain 😕 Maybe someone knows how to do it better.
Anyway that's why I add option to automatically close app after clean process.

> I know it might be too much to request for. I appreciate your hard work and time. I will keep using your amazing app either way.

No worries, I'm glad to see new requests, but it depends on my skills and time. I spent a lot of time to implement widget but due to luck of knowledge I abandoned it. I have no idea how to do it 😭

> It would be awesome if it could be implemented in the F-Droid version of the app. If it wont be a hassle to you of course.

I will think about it but only after New Year⛄🎁

**Comment by TPS** [comment]
This would be an amazing option for https://github.com/bmx666/android-appcachecleaner/issues/244, also.

**Comment by bmx666** [comment]
After migration on Jetpack Compose it's much easy to implement, so this feature will be soon.
Stay tune 😄

**Comment by TPS** [comment]
As before, will feedback when this hits F-droid.

**Comment by TPS** [comment]
@bmx666 This has landed on F-droid, & though I enable "Allow clear data - DANGER!" setting, the actual button isn't another mode on the main screen as I expected, but an additional red trash button during regular cache cleaning.  That makes me a bit nervous, but works well on the disabled apps I tried.

An additional "Are you sure?" _would_ be nice for safety reasons.  I'll be generally keeping it off, just b/c I'm klutzy, but will re-enable when I'm particularly aware.

Thanks very much! 🙇🏾‍♂️

**Comment by bmx666** [comment]
Hey @TPS 

> An additional "Are you sure?" would be nice for safety reasons. I'll be generally keeping it off, just b/c I'm klutzy, but will re-enable when I'm particularly aware.

There's already warning dialog on all possible languages when you press "red button". At least, I'm also clumsy and keep it off 😁

**Comment by TPS** [comment]
I mean, also when _enabling_ setting.  Can't have too many belt-&-suspenders when trying to kill app-data.

**Comment by bmx666** [comment]
That's why I didn't want to implement this dangerous featureat the beginning 😂
