### ISSUE TITLE
Important 

### ISSUE THREAD

**Issue by hossamkarimo** [bmx666/android-appcachecleaner#164]
Search Button
He wished to add a feature to search for an application by name

**Comment by bmx666** [comment]
Hi @hossamkarimo, could you please provide more information? The list of apps is sorted in descending order by cache size. If you wish to clean specific apps, go to **Settings** and create a **Custom List**.

**Comment by bmx666** [comment]
@hossamkarimo if you have no questions I will close this issue

**Comment by hossamkarimo** [comment]
In the top bar, I would like to search by the name of the application

**Comment by bmx666** [comment]
Hi @hossamkarimo , the Cache Cleaner shows list of apps (for Android 8 and later) sorted by cache size from the biggest. As I said before, go to Settings and create custom list with your specific apps.
