### ISSUE TITLE
Can I translate it?

### ISSUE THREAD

**Issue by Gamefire238** [bmx666/android-appcachecleaner#186]

**Comment by bmx666** [comment]
Hi @Gamefire238 what language do you want to support?

**Comment by Gamefire238** [comment]
Indonesia
Do I just have to set it?

**Comment by bmx666** [comment]
There is no support for the Indonesian language yet.

**Comment by bmx666** [comment]
Please review translated file -> https://github.com/bmx666/android-appcachecleaner/pull/187/files
if you find something, please leave a comment in the appropriate line about the correct translation.
