### ISSUE TITLE
[feature request] - Add a setting to disable the quicksetting tile nag

### ISSUE THREAD

**Issue by christopherdriscoll** [bmx666/android-appcachecleaner#189]
Each time I launch the app It wants to add a tile to quicksettings.  It'd be a welcome addition to disable the nag.

Thank you for your work on the app!

**Comment by bmx666** [comment]
Hi @christopherdriscoll Cache Cleaner Tile Service does not do anything in background, only when user add Tile on Panel to check status of permission once to set icon state. If you add into background is it really hurt?
I could not reproduce your case, even after update I didn't get nag.

**Comment by christopherdriscoll** [comment]
If it helps, I'm using the F-Droid build.

Not sure why I would add the tile when that's not how I'm interacting with the application vs. having that behind a toggle in the app.

Using a Pixel 7 Pro, Android 14, January security update.

**Comment by bmx666** [comment]
I checked on my phone (Android 14, Sony Xperia Mark 1 V) of F-Droid version:

* install 1.10.3
* deny 3 times
* update on 1.10.5
* no requests

Basic registration as ComponentName:

```kotlin
getSystemService(StatusBarManager::class.java)?.requestAddTileService(
            ComponentName(
                this,
                CacheCleanerTileService::class.java
            ), ...)
```

Maybe Pixel resets or erase something?
Could you raise an issue on Google Issue Tracker about that behavior?
