### ISSUE TITLE
No apk for 1.10.6

### ISSUE THREAD

**Issue by linsui** [bmx666/android-appcachecleaner#194]
F-Droid needs that for reproducible build. Could you please upload it? Thanks!

**Comment by bmx666** [comment]
Hi @linsui sorry, I just release quick fix for Google Play build variant, nothing related to F-driod and tag v1.10.6 could be skipped, no updates.

**Comment by linsui** [comment]
Got it, thanks!

**Comment by linsui** [comment]
> There is no fastline notes about this release and could it be a problem?

No. And it's always optional. :)
