### ISSUE TITLE
App Info issue

### ISSUE THREAD

**Issue by crashtitude** [bmx666/android-appcachecleaner#203]
![Screenshot_20240215-061342_Pembersih Cache](https://github.com/bmx666/android-appcachecleaner/assets/108076778/d53ae699-97da-48a6-8e99-d8c638f5c245)
This log error report

**Comment by bmx666** [comment]
Hi @crashtitude ,

Android 14 has a system bug. Please check #190 
I'm waiting when fix will be delivered by Google in a new Android 14 update.
