### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [bmx666/android-appcachecleaner#210]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6348557804#L860

look like your APK in https://github.com/bmx666/android-appcachecleaner/releases/tag/v1.10.11 was NOT built from the tagged commit bb00c8620f947f940f2a96b8c3d362c109eced3f

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/7dfcccb5ba515729ed031671fb6639c276cc3398

**Comment by bmx666** [comment]
Hi @licaon-kter 

Thanks for update, hmm, strange, but anyway I checkout on v1.10.11, rebuild APK again and re-upload into release.

**Comment by licaon-kter** [comment]
that's better https://gitlab.com/fdroid/fdroiddata/-/jobs/6349948252#L919

reenabled: https://gitlab.com/fdroid/fdroiddata/-/commit/066b339c80b5b6696e2f5d51654ae1ccbae3b955

**Comment by licaon-kter** [comment]
and again: https://gitlab.com/fdroid/fdroiddata/-/jobs/7648835805#L1558

diff log: [appcl93.log.zip](https://github.com/user-attachments/files/16726884/appcl93.log.zip)

**Comment by bmx666** [comment]
Hi @licaon-kter , thanks for update.
It seems that Android Studio isn't rebuilding or regenerating new APK binaries, even after switching to a different commit with identical changes. Nevertheless, I performed a clean rebuild and uploaded a new APK. I will ensure to make a clean rebuild before uploading future releases. Sorry for the inconvenience.

**Comment by licaon-kter** [comment]
Thanks

**Comment by bmx666** [comment]
I created an issue on Google Issue Tracker -> https://issuetracker.google.com/issues/361746103
I hope someone can explain this behavior.

**Comment by licaon-kter** [comment]
hmm, https://gitlab.com/fdroid/fdroiddata/-/jobs/7852041468#L2332 can you reopen?

diff log: [Uploading cache101.log…]()

**Comment by bmx666** [comment]
Google recently add compose-compiler, I did clean release build as before, I have no idea why error is appearing.

**Comment by licaon-kter** [comment]
diff log: [cache101.log](https://github.com/user-attachments/files/17044202/cache101.log)

**Comment by bmx666** [comment]
I upload new clean release build again, it's the same...

**Comment by bmx666** [comment]
Here new patch that includes compose-compiler from Google
https://github.com/bmx666/android-appcachecleaner/commit/372656cebec22974cd1a8b797da448fa898dad77

**Comment by bmx666** [comment]
I will update Android Studio and SDK manager and re-upload new clean release APK

**Comment by bmx666** [comment]
I made a new release - https://github.com/bmx666/android-appcachecleaner/releases/tag/v2.2.4

**Comment by bmx666** [comment]
There is another possible issue could be - https://developer.android.com/build/releases/gradle-plugin#groovy

>  Caution: You should not use dynamic dependencies in version numbers, such as 'com.android.tools.build:gradle:8.6.+'. Using this feature can cause unexpected version updates and difficulty resolving version differences.

Time to release a new release...

**Comment by bmx666** [comment]
@licaon-kter  Sorry for the mess, Google never lets developers stay chill... 😞 
https://github.com/bmx666/android-appcachecleaner/releases/tag/v2.2.5
