### ISSUE TITLE
I don't understand how to enable accessibility 

### ISSUE THREAD

**Issue by FaqatZubair1** [bmx666/android-appcachecleaner#215]
Can you please make a video tutorial in which you teach how to use the app and enable required settings on Android 14. I am not able to turn on any required settings on my Motorola phone.
Edit: I just installed your app from Play Store and it works well. But when I installed it previously from github, it didn't work, because Google didn't let me to allow permissions for this app.

**Comment by bmx666** [comment]
Hi @FaqatZubair1 

Please read README https://github.com/bmx666/android-appcachecleaner#warning-%EF%B8%8F or check the Help menu (this option is hidden for Google play)

**Comment by bmx666** [comment]
Hi @FaqatZubair1 , I made a video on main page and in menu Help [Watch TUTORIAL on YouTube](https://www.youtube.com/watch?v=UiCr33gYZiI) since version 1.11.3
