### ISSUE TITLE
Progress icon persists if force closed

### ISSUE THREAD

**Issue by ZimCodes** [bmx666/android-appcachecleaner#228]
## Description
When the app is in the process of clearing caches, an icon appears on the user's device indicating the current progress. If the user force closes all apps _(or just the Settings app)_, the app would correctly stop clearing caches, but the icon showing the progress persists indefinitely unless the user resets their device.

## Steps to reproduce
1. Open app
2. Select any of the 3 options _(I chose **Clean Cache of User Apps**)_
3. Select any 3+ from the list of apps, services, and processes
4. Select the broom button to start.
5. While the app clears the caches, open your app switcher and force close all apps _(or just the Settings app)_. 
6. For now on, the progress icon will stay on your screen indefinitely, unless you reset your device.

## Correct Behavior
If the user force closes the settings app while the cache cleaner app is active, the progress icon should no longer persist.

**Comment by bmx666** [comment]
Hi @ZimCodes , sorry for the long reply. I had no time.
I updated Accessibility service, please check a new version v1.11.3 and let me know.

**Comment by ZimCodes** [comment]
Yes, this update fixed the issue.

The new behavior is after force closing using the app switcher, the icon will disappear after a while. 

Thanks for fixing this issue!
