### ISSUE TITLE
cache-cleaner unable to process for "professional" profile (using shelter)

### ISSUE THREAD

**Issue by lm2lm2** [bmx666/android-appcachecleaner#232]
hello

im trying to use cache-cleaner to do the same of "personal profile", but in the "professional" one (using shelter)
the app opens well, i can well "enable" the module, it can well detect the apps of the shelter, but : when checking all box for each app and "start cleaning", it just stops, do nothing..

**Comment by bmx666** [comment]
Hi @lm2lm2, I have no idea what's shelter and "professional" profile.

**Comment by lm2lm2** [comment]
> Hi @lm2lm2, I have no idea what's shelter and "professional" profile.

hi, shelter is a fdroid OSS app allowing to create a kind of sub/alternative /sdcard profile to ensure all apps could be used with other data.

eg if you try with others  fdroid apps, eg messaging apps, it allows you to use several accounts with app who doesnt manage several accounts.
it's a kind of "second virtual smartphone" that isolates into a "data box" the usage of a specific app, by using two profiles : personal and professional.

have a look! :)

**Comment by bmx666** [comment]
Did you check if sdmain behaves similar? 
https://github.com/d4rken-org/sdmaid/issues/5133

**Comment by bmx666** [comment]
no reply
