### ISSUE TITLE
[feature request] support root mode

### ISSUE THREAD

**Issue by Mahantor** [bmx666/android-appcachecleaner#243]
Please add root mode to the app for rooted phones

**Comment by TPS** [comment]
@Mahantor https://github.com/bmx666/android-appcachecleaner/issues/198

@bmx666 Maybe Shizuku support instead/also?

**Comment by bmx666** [comment]
Hi @TPS @Mahantor 

What is your suggestion? If you plan to avoid using **Accessibility Service**, then Cache Cleaner is not suitable for that. The main purpose of Cache Cleaner is to perform clicks, nothing more. If you want to call or execute root commands that run in the background, then this concept doesn't fit.

**Comment by TPS** [comment]
@bmx666 More than simply avoiding the A11y Service, it's about _speed_.  Using `adb` (Shizuku)/`root` for these functions can accomplish in _seconds_ what would typically take minutes.  Wating for 1's device to perform maintenance is boring, & this would help ameliorate that.

**Comment by bmx666** [comment]
In that case, I suppose couldn't provide any solution without external support from other maintainers that could develop app and focus on root mode feature.
Maybe PR would be helpful, but it's out of my scope.

**Comment by TPS** [comment]
@bmx666 Unfortunately, I'm no Android developer.  In case you or anyone'd like to take a look, I linked the [Shizuku (& SUI) API](https://github.com/RikkaApps/Shizuku-API) above.  Perhaps it'd be a good start point?

**Comment by bmx666** [comment]
@TPS not really, it takes a lot of effort to integrate just their API into app itself.

**Comment by bmx666** [comment]
Please have a look into https://github.com/bmx666/android-appcachecleaner/issues/250#issuecomment-2267487934

I think scripts that calls via Magisk the best option for your cases.

**Comment by TPS** [comment]
Magisk also requires `root`, while Shizuku runs via `adb` _w/o_ needing that.  Maybe leave this open for potential PR?

**Comment by bmx666** [comment]
@TPS  if you have access to `adb` with root access, or any Terminal app with root access then just type in shell
```
find /data/data/*/cache/* /data/data/*/code_cache/* /data/user_de/*/*/cache/* /data/user_de/*/*/code_cache/* /sdcard/Android/data/*/cache/* -delete &>/dev/null
```

**Comment by TPS** [comment]
If 1 were to have `root`/`sui`, 1 doesn't need `adb`/`Shizuku`.  The latter is a way to achieve many functions _sans_ `root` that're not otherwise available, such as many filesys ops.
