### ISSUE TITLE
[feature request] button for clean cache of disabled apps

### ISSUE THREAD

**Issue by TPS** [bmx666/android-appcachecleaner#244]
@bmx666 An inverse request to https://github.com/bmx666/android-appcachecleaner/issues/135, could there be the option to _always/only_ show disabled apps (ignoring other filters, e.g., app cache size)  I run into disabled apps that still have app cache/data, which is just a complete waste of space.

**Comment by bmx666** [comment]
Hi @TPS 

I think the simplest solution would be just create additional button "clean cache of disabled apps" with optional visibility (checkbox in the Settings) on main screen.

**Comment by TPS** [comment]
Thanks for considering my request. 🙇🏾‍♂️

**Comment by bmx666** [comment]
Hi @TPS

Done, check version [v1.12.1](https://github.com/bmx666/android-appcachecleaner/releases/tag/v1.12.1)

**Comment by TPS** [comment]
Amazing!  I'll test it when F-Droid builds/releases it & I'll feedback. 🙇🏾‍♂️

**Comment by TPS** [comment]
@bmx666 I wanted to let you know this works well just as designed.  Maybe an optimization could be to have a toggle that disables the minimum threshold for this function only?

**Comment by bmx666** [comment]
Hi @TPS , do you mean reset min. cache size filter to 0 bytes?

**Comment by TPS** [comment]
> Hi @TPS , do you mean reset min. cache size filter to 0 bytes?

Basically, just ignore it, so equivalent to _temporarily_ resetting to 0 while running that.

> UPD: Seems reasonable and easy fix, check new v1.12.3

I'll again feedback when it releases on F-droid.

**Comment by TPS** [comment]
> Hi @TPS , do you mean reset min. cache size filter to 0 bytes?
> 
> UPD: Seems reasonable and easy fix, check new v1.12.3

This works perfectly.  Thanks, @bmx666 🙇🏾‍♂️
