### ISSUE TITLE
It is not deleting all cache

### ISSUE THREAD

**Issue by Ultimateepic00** [bmx666/android-appcachecleaner#25]
I gave the app accessibility permission but when i try to remove all cache from the selected apps it was working with some apps only, For example Instagram has 450mb of cache, The app only removed 300mb leaving 150mb, With some apps it is not deleting any cache at all but for others it delete all of its cache

**Comment by bmx666** [comment]
Hi @Ultimateepic00 

Android show sum of two separated cache places - internal private cache (/data/data/com.my.package/cache) and external public cache (on /sdcard/Android/...).
Android never clears the external public cache, only when you uninstall app.
