### ISSUE TITLE
Interrupted Cache Cleaner Was interrupted by the android system while cleaning apps.

### ISSUE THREAD

**Issue by megvadulthangya** [bmx666/android-appcachecleaner#250]
Hi! Looks like this app is broken on my device after updating to the latest version...  :(
Im on Lenovo K6 (Crdroid...  Android 11)

**Comment by bmx666** [comment]
Hi @megvadulthangya 

Do you have this issue on v1.12.0 ?

**Comment by megvadulthangya** [comment]
> Do you have this issue on [v1.12.0](https://github.com/bmx666/android-appcachecleaner/releases/tag/v1.12.0) ?

I can confirm v12 is working ok.

Can i ask using your app is the same as if i go to recovery then, wipe, then andvanced wipe tick cache and dalvik/ART cache?

Or... do the magisk module [cache cleaner](https://github.com/takeru-kageyuki/cache_cleaner)?

**Comment by bmx666** [comment]
Hi @megvadulthangya 

Nice that v12 works.

Perform click on "Clean cache" button triggers Android system to clean only

/data/data/*/cache/*
/data/user_de/*/*/cache/*

**Comment by megvadulthangya** [comment]
Thank you for your time!
