### ISSUE TITLE
Light mode?

### ISSUE THREAD

**Issue by kyoyacchi** [bmx666/android-appcachecleaner#255]
The app opens in dark mode as default, so toggling off or on "dark mode" option does nothing.

**Comment by bmx666** [comment]
Hi @kyoyacchi 

Settings -> UI -> Night Mode was made to Force use Night mode.
Do you want Force Light mode as an option too?

**Comment by kyoyacchi** [comment]
> Hi @kyoyacchi 
> 
> Settings -> UI -> Night Mode was made to Force use Night mode.
> Do you want Force Light mode as an option too?

No, no. What i meant is this;

https://github.com/user-attachments/assets/cf77884c-6311-443b-a6f2-f9ce1cc0f744

**Comment by bmx666** [comment]
App sets the system theme (dark or light) by default.
It will affects only if you have light theme, and want to set FORCE dark theme.

**Comment by kyoyacchi** [comment]
That's a bit odd but OK. At first i thought it was kinda bug. I think you can make make it visible if user uses light mode on their phone or sum. Have it your way ofc.

**Comment by bmx666** [comment]
@kyoyacchi  long time ago someone asked to add force night mode option, I did it, that it.
