### ISSUE TITLE
releases on accrescent

### ISSUE THREAD

**Issue by atlantis451** [bmx666/android-appcachecleaner#270]
https://github.com/accrescent/accrescent
https://github.com/accrescent/parcelo Accrescent developer console.

> Accrescent is a private and secure Android app store built with modern features in mind. It aims to provide a developer-friendly platform and pleasant user experience while enforcing modern security and privacy practices and offering robust validity guarantees for installed apps.

**Comment by bmx666** [comment]
Hi @atlantis451 

To get access I must have invitation 😭 
Anyway, F-Droid team are taking care about configuration and release tracking by itself. I do nothing, just upload releases on GitHub.

**Comment by bmx666** [comment]
Please check yaml file on F-Droid and create on Accres cent
