### ISSUE TITLE
Improve Force Stop

### ISSUE THREAD

**Issue by bmx666** [bmx666/android-appcachecleaner#271]
Sometimes there is no Force Stop dialog title, and it would be great to find Cancel button nearby to predict if it's dialog or not.

**Comment by TPS** [comment]
Here's another log from same debug build.  I'm not sure what you're diagnosing is the problem?  The "app info" for target app comes up fine 8-10×, but there is _no_ "force stop" dialog that I perceive that shows.

![appcachecleaner-log2.txt.zip](https://github.com/user-attachments/files/16847750/appcachecleaner-log2.txt.zip)

**Comment by bmx666** [comment]
@TPS at first event it return AppInfo tree view and I run scenario

> [07:07:07.849] D: ===>>> TREE BEGIN <<<===
> ...
> [07:07:08.030] D: ===>>> TREE END <<<===
> [07:07:08.039] D: findForceStopDialogTitle: found title = false
> [07:07:08.091] D: found force stop button
> [07:07:08.092] D: force stop button is enabled
> [07:07:08.157] D: perform action click on force stop button

Then Accessibility service sends new event "Force stop dialog"

> [07:07:08.245] D: ===>>> TREE BEGIN <<<===
> [07:07:08.250] D: [508286197]  android.widget.FrameLayout:null:null
> [07:07:08.252] D: [508286197] > android.widget.FrameLayout:null:null
> [07:07:08.252] D: [508286197] >> android.widget.FrameLayout:null:null
> [07:07:08.253] D: [508286197] >>> android.widget.LinearLayout:null:com.android.settings:id/action_bar_root
> [07:07:08.253] D: [508286197] >>>> android.widget.FrameLayout:null:android:id/content
> [07:07:08.254] D: [508286197] >>>>> android.widget.LinearLayout:null:com.android.settings:id/parentPanel
> [07:07:08.255] D: [508286197] >>>>>> android.widget.LinearLayout:null:com.android.settings:id/contentPanel
> [07:07:08.255] D: [508286197] >>>>>>> android.widget.ScrollView:null:com.android.settings:id/scrollView
> [07:07:08.256] D: [508286197] >>>>>>>> android.widget.TextView:Exceptions may occur if an app is force stopped.:android:id/message
> [07:07:08.256] D: [508286197] >>>>>>> android.widget.LinearLayout:null:com.android.settings:id/listPanel
> [07:07:08.257] D: [508286197] >>>>>> android.widget.LinearLayout:null:com.android.settings:id/buttonPanel
> [07:07:08.258] D: [508286197] >>>>>>> android.widget.Button:Force stop:android:id/button1
> [07:07:08.259] D: [508286197] >>>>>>> android.widget.ImageView:null:com.android.settings:id/coui_dialog_button_divider_2
> [07:07:08.259] D: [508286197] >>>>>>> android.widget.Button:Cancel:android:id/button2
> [07:07:08.260] D: ===>>> TREE END <<<===
> [07:07:08.262] D: findForceStopDialogTitle: found title = false
> [07:07:08.267] D: found force stop button
> [07:07:08.267] D: force stop button is enabled
> [07:07:08.271] D: perform action click on force stop button

Expected Force Stop dialog title - "Force stop?" (multi language), it because it was not found, it switch back to scenario - Find "Force stop" button (but because Dialog and AppInfo have the Button widget view with text "Force stop")

> android.widget.Button:Force stop:com.android.settings:id/middle_button
> android.widget.Button:Force stop:android:id/button1

On Default AOSP there is not "Force Stop", it's only OK or CANCEL. Your UI is unique.

**Comment by bmx666** [comment]
Example of Default AOSP UI

![image](https://github.com/user-attachments/assets/a81fa8b2-0a2c-4bfe-9cad-0afd68eb74ab)

**Comment by bmx666** [comment]
@TPS please check this test debug version - [app-debug.apk.zip](https://github.com/user-attachments/files/16850601/app-debug.apk.zip) (just rename attached file into app-debug.apk)

**Comment by TPS** [comment]
> Your UI is unique.

I've a 1+ device.  I didn't realize that got changed.

![appcachecleaner-log3.txt.zip](https://github.com/user-attachments/files/16860077/appcachecleaner-log3.txt.zip)

Here's the log from that last debug.  I think that worked?  I'll test further & report back.

**Comment by bmx666** [comment]
Thanks for the report. Yes, it's fine. I will create a new release soon that includes this fix.

**Comment by mirror176** [comment]
I presume this improvement should work without any extra options but were there any settings to change to use it? I have a dialog similar to that of the one above but a little different:

Force stop
If you force stop an app, it may cause errors.
Cancel    OK

Differences of no question mark and the last word. If logging is needed, is it only available from removing the fdroid version and installing the github debug version?
