### ISSUE TITLE
Accessibility option won't show unless app is session-installed

### ISSUE THREAD

**Issue by 77-77SP** [bmx666/android-appcachecleaner#272]
I would like to propose adding a small notice in the help section of the app to notify users that the accessibility setting of the app can be only enabled if the app is installed using a session based method (such as play store, f-droid, SAI).

It is a small effort that will solve potential issues in the future.

Thank you.

**Comment by 77-77SP** [comment]
Further reading:  
https://www.esper.io/blog/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis

**Comment by bmx666** [comment]
@77-77SP it's already in help for Android 13 and later, also link on YouTube video, and here in README. I didn't get what you need 😭

**Comment by 77-77SP** [comment]
> @77-77SP it's already in help for Android 13 and later, also link on YouTube video, and here in README. I didn't get what you need 😭

I read again the sources you mentioned but I does not address my case. When installing the app in a certain way (using file managers mostly), the Accessibility setting will not show (and following the documentation will not resolve it) unless re-installed using the session-install API.

This will mostly happen when a user installs the app from file managers.

**Comment by bmx666** [comment]
Did you watch YouTube video?

**Comment by bmx666** [comment]
anyway, could you provide record video or screenshots?

**Comment by 77-77SP** [comment]
> Did you watch YouTube video?

Yes I did but even following these steps will not work if the app is installed in a non session based install (such as from file managers). 
Installing the app from f-droid and following the video solves the issue and the setting can be enabled.

**Comment by 77-77SP** [comment]
It would be great if someone could chip in try and reproduce the situation I am trying to convey by installing the app from a file manager and trying to enable the accessibility setting.

**Comment by 77-77SP** [comment]
I would like to iterate that the situation I am refering to is not caused by the app but the OS.

I thought that adding the notice would help users who might share the same situation.

Unfortunately I am unable to prodive screen capture. I will be glad if someone else who has the same situation would like to corroborate.

Sorry for any inconvenience.

**Comment by bmx666** [comment]
Sorry, but I didn't understand you.
I didn't have any kind of these issues on Default AOSP ( Emulator and Sony Xperia). Please share your phone and Android OS build type.

**Comment by bmx666** [comment]
I checked on my side, install from f-droid (no need to allow restriction), update from local (go to AppInfo and allow restriction). No issues. 
Install from local (go to AppInfo, allow restriction), update from F-Droid (no need to allow restriction). No issues.
Sorry, but I couldn't reproduce it on Default AOSP.
Again: Please tell me your phone and Android OS build type.
