### ISSUE TITLE
selective cleaning

### ISSUE THREAD

**Issue by despicere** [bmx666/android-appcachecleaner#278]
version 2.2.1 after selective cleaning continues to pull unselected applications. Fix it.

**Comment by bmx666** [comment]
Hey @despicere .
Could you please provide more information? Fix what?

**Comment by despicere** [comment]
Clear cache of selected applications and stop! Do not sort through further. I do not have time to understand. Not selected or selected after cleaning runs again. Very quickly flickers and twitches.

**Comment by bmx666** [comment]
no response
