### ISSUE TITLE
Проблема при очистки

### ISSUE THREAD

**Issue by Paola-bt** [bmx666/android-appcachecleaner#281]
Iqoo z9x
Android 14
v2.2
Попытайтесь исправить.
При попытки очистки ничего не происходит, приходиться завершать работу приложения. Log с app-debug.apk прилагаю:
[appcachecleaner-log.txt](https://github.com/user-attachments/files/17005170/appcachecleaner-log.txt)

Если дождаться завершения работы приложения log файл создаётся пустым.

**Comment by bmx666** [comment]
Hey, @Paola-bt 

Did you read in the Help menu a section about Customized UI?

> android.widget.TextView:Память:com.android.settings:id/title

But app is looking for - `Хранилище и кэш` OR `Хранилище`, default transition of `Storage` for Russian language.

https://github.com/bmx666/android-appcachecleaner/blob/372656cebec22974cd1a8b797da448fa898dad77/app/src/main/res/values-ru/strings.xml#L373

**Comment by Paola-bt** [comment]
Да. А что тогда приложение должно искать?
![01](https://github.com/user-attachments/assets/0d95b028-4fe2-444d-91cf-6fab3d251db5)
![02](https://github.com/user-attachments/assets/683cf880-44fc-4984-8b11-e3251a0131ba)

**Comment by bmx666** [comment]
There are algorithms:

For default scenario 
https://github.com/bmx666/android-appcachecleaner/blob/372656cebec22974cd1a8b797da448fa898dad77/app/src/main/java/com/github/bmx666/appcachecleaner/clearcache/scenario/DefaultClearScenario.kt#L21-L53

and for Xiaomi scenario
https://github.com/bmx666/android-appcachecleaner/blob/372656cebec22974cd1a8b797da448fa898dad77/app/src/main/java/com/github/bmx666/appcachecleaner/clearcache/scenario/XiaomiMIUIClearScenario.kt#L12-48

**Comment by bmx666** [comment]
Did you try to clean cache or clear data?

**Comment by Paola-bt** [comment]
Спасибо. Надо было в "Очистить кеш"- внести "Очистить кэш", а в "Хранилище и 
кеш"- добавить "Память".

Есть ещё один момент, приложение неправильно определяет размер кэша Newpipe и Pipepipe. Например:
![01](https://github.com/user-attachments/assets/24709937-fad6-407c-9e8e-90b4861e5549)
![02](https://github.com/user-attachments/assets/a882605d-1320-4e78-8ea9-251b98bfb89d)

**Comment by bmx666** [comment]
Please read about it here (and link in comment) - https://github.com/bmx666/android-appcachecleaner/issues/214#issuecomment-1997773210
