### ISSUE TITLE
App is clicking wrong item for "storage & cache" under certain conditions 

### ISSUE THREAD

**Issue by steve51184** [bmx666/android-appcachecleaner#283]
So I have a custom change for the "storage and cache" name as mine has an ampersand instead of an "and" and after a recent update it now seems to ignore the "&" and will click the first thing with "storage" which is mostly "storage & cache" but if the permissions tab has just "storage" selected it'll choose that instead and won't clean the cache as it'll be on the permissions page..

Hope that makes sense or I can post a video :)

**Comment by bmx666** [comment]
Hi @steve51184 , should be fixed in v2.2.3. If you set extra search text in the Settings, then Cache Cleaner will use only this text to find matched view. In prev, it just used on top of the searching list, that's why it doesn't work properly. Hard to cover many devices at once.

**Comment by steve51184** [comment]
Tested v2.2.3 and the problem is still there..

**Comment by steve51184** [comment]
@bmx666 Tested v2.2.3 and the problem is still there..

**Comment by steve51184** [comment]
Ty confirmed fixed 😀
