### ISSUE TITLE
Can I write a Turkish patch for your application?

### ISSUE THREAD

**Issue by doilbreak** [bmx666/android-appcachecleaner#289]

**Comment by bmx666** [comment]
Hi @doilbreak , I translated text with ChatGPT here -> [#291](https://github.com/bmx666/android-appcachecleaner/pull/291/files)
Please review and add comment ("+" button), and I will update translation.

If you want, you can download XML-file (https://raw.githubusercontent.com/bmx666/android-appcachecleaner/6d288f2cc01410ccb47b3f685ef65ad05adbd8e6/app/src/main/res/values-tr/strings.xml) and translate in Notepad or other text editor and attach here with correct translation.

**Comment by bmx666** [comment]
Hi @doilbreak , why did you close issue?

**Comment by doilbreak** [comment]
I apologize, I did not write it, chatgpt has done a near perfect job, you can use it without any problems.
