### ISSUE TITLE
Невозможно дать разрешение спец возможностей

### ISSUE THREAD

**Issue by Prynka1995** [bmx666/android-appcachecleaner#29]
Добрый день,

нет ползунка, чтобы дать разрешение приложению к спец возможностям android
![photo_2022-12-19_10-19-41](https://user-images.githubusercontent.com/35833727/208369704-eaaaec68-14e8-4cc0-9b81-fe09131e0af8.jpg)
![photo_2022-12-19_10-19-45](https://user-images.githubusercontent.com/35833727/208369706-030189db-22c4-4d8d-bc27-0a0f1ebbecb0.jpg)

**Comment by bmx666** [comment]
Hi @Prynka1995
Cache Cleaner app uses a mechanism to request accessibility provided by Android. Something is blocking it in your Android ROM. This issue is not related to the app.
