### ISSUE TITLE
Request: Clear data of apps in custom lists.

### ISSUE THREAD

**Issue by BrendonIrwan** [bmx666/android-appcachecleaner#292]
With 2.2.5, selecting the option to `Clean cache of custom list` does not allow clearing of data, despite having the `Allow clear data` option enabled.

My suggestion is to--instead of directly starting the cleanup procedure--show the list of apps in the selected custom list, just like with the other `Clean cache of [...]` options. That way the user can review what's in the custom list, and might as well hit the red button if enabled.

**Comment by bmx666** [comment]
Hi @BrendonIrwan , sounds reasonable, I will check what I can do.

**Comment by bmx666** [comment]
In new version v2.2.6 when you click on clear cache of custom list, you can click extra button "Filter".

**Comment by BrendonIrwan** [comment]
Confirmed. Thanks!
