### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by pyccl** [bmx666/android-appcachecleaner#297]

**Comment by bmx666** [comment]
Hi @pyccl there are several types of Chinese in Android:

* Chinese (Simplified Han, China)
* Chinese (Simplified Han, Hong Kong)
* Chinese (Simplified Han, Macau)
* Chinese (Simplified Han, Singapore)
* Chinese (Traditional Han, Macau)
* Chinese (Traditional Han, Taiwan)
* Chinese (Traditional Han, Hong Kong)

Which version you can review?

**Comment by pyccl** [comment]
> Hi @pyccl there are several types of Chinese in Android:
> 
> * Chinese (Simplified Han, China)
> * Chinese (Simplified Han, Hong Kong)
> * Chinese (Simplified Han, Macau)
> * Chinese (Simplified Han, Singapore)
> * Chinese (Traditional Han, Macau)
> * Chinese (Traditional Han, Taiwan)
> * Chinese (Traditional Han, Hong Kong)
> 
> Which version you can review?

Chinese (Simplified Han, China)Thinks！

**Comment by bmx666** [comment]
Hi @pyccl , I translated text with ChatGPT here -> #299 
Please review and add comment ("+" button), and I will update translation.

If you want, you can download XML-file (https://github.com/bmx666/android-appcachecleaner/blob/ff928f31d8e069176d88f6b9ec6eabbe2817952e/app/src/main/res/values-zh-rCN/strings.xml) and update incorrect translation in Notepad or other text editor and attach here with correct translation.
