### ISSUE TITLE
App is totally useless now!

### ISSUE THREAD

**Issue by farhanrejwan** [bmx666/android-appcachecleaner#298]
Just as the title says. Let alone cleaning cache, app doesn't even open the app info of any app so that at least I could manually clean the cache. It used to work in the previous 1.x.x version that I was using (I don't remember which one it was), but many days have passed and I came here to check for updates, only to see that the latest version is now some 2.x.x. So I don't know where things actually started going wrong or how to fix them, since I've tried all methods according to the help manual and none of them worked. The only remaining option I can give is, my device is Xiaomi Redmi Note 7 and the OS is Android 10. Hope things get fixed.

**Comment by bmx666** [comment]
Hi @farhanrejwan , could you please install debug version and attach generated log here? (Just clean few apps)

https://github.com/bmx666/android-appcachecleaner/releases/download/v2.2.7/app-debug.apk

**Comment by bmx666** [comment]
duplicate #296
