### ISSUE TITLE
Add this app to fdroid

### ISSUE THREAD

**Issue by CodeCubeNeo** [bmx666/android-appcachecleaner#3]

**Comment by bmx666** [comment]
Already in progress 😄 
https://gitlab.com/fdroid/rfp/-/issues/2094

**Comment by shuvashish76** [comment]
Update:

Marked as "Ready", now its just about time. Someone needs to pick it up create the metadata and the merge request.

For now deGoogled users can install it from [izzy-repo](https://apt.izzysoft.de/fdroid/index/apk/com.github.bmx666.appcachecleaner)
