### ISSUE TITLE
work profile issue

### ISSUE THREAD

**Issue by wandersoncode** [bmx666/android-appcachecleaner#306]
I installed the app on the work profile and it does not seem to do anything. I click on the erase icon and it just moves back to the app landing page.

I am on the latest version of the app from fdroid

**Comment by bmx666** [comment]
Hi @wandersoncode

For devices running on work profile mode, the app needs to be installed in the personal profile to be able to use it.

Also Accessibility has a lot of restrictions for Work Profile and could be disabled by Admin.

**Comment by wandersoncode** [comment]
hey @bmx666. Thank you for getting back so quickly. 

- I do have the app installed on the personal and work profile. Personal profile works perfectly. 
- regarding the work profile, I am just using shelter to set it up, so technically the shelter app is the admin there and not owned by any external entity. 

would that  change the scenario or do you still believe just being the work profile causes things to not work as expected?

**Comment by bmx666** [comment]
Hi @wandersoncode it's the same issue - #232

**Comment by wandersoncode** [comment]
Thanks @bmx666. I read more about it and understand now. Appreciate your patience.
