### ISSUE TITLE
Cache cleaning cannot be performed on Samsung tablets.

### ISSUE THREAD

**Issue by ggsmida0329** [bmx666/android-appcachecleaner#308]
On my Samsung Tab S6, it freezes during the cleaning process. I tried using the 'Customized Settings UI,' but it didn’t help. However, everything works perfectly on my Samsung S20 FE.
![Screenshot_20241112_214003_Settings](https://github.com/user-attachments/assets/2536e543-1e85-4121-91c1-a2447cddb08d)
![Screenshot_20241112_214024_Settings](https://github.com/user-attachments/assets/5d9f0897-ee4f-47de-850d-7f33c131b845)

https://github.com/user-attachments/assets/2597355b-4380-41a9-b9ed-4cef414d6d46

**Comment by bmx666** [comment]
Hi @ggsmida0329 , from first look you have very customized UI.
Could you please download [debug version](https://github.com/bmx666/android-appcachecleaner/releases/download/v2.2.9/app-debug.apk), select 1-2 apps and wait until log file will be generated and attach here.
Please switch system language on English, it will be easy to read debug log.

**Comment by ggsmida0329** [comment]
> Hi @ggsmida0329 , from first look you have very customized UI. Could you please download [debug version](https://github.com/bmx666/android-appcachecleaner/releases/download/v2.2.9/app-debug.apk), select 1-2 apps and wait until log file will be generated and attach here. Please switch system language on English, it will be easy to read debug log.

I switched the system language to English. Here is my debug log.
[appcachecleaner-log.txt](https://github.com/user-attachments/files/17742191/appcachecleaner-log.txt)

**Comment by bmx666** [comment]
Hi @ggsmida0329 , thanks for the attached log.

Cache Cleaner found View element "Storage" and did perform click on it, but nothing happened:
`
D: [14920477] >>>>>>>>>>>>>>>>>>>>> android.widget.TextView:Storage:android:id/title
D: [14920477] >>>>>>>>>>>>>>>>>>>>> android.widget.TextView:1.33 GB used in Internal storage:android:id/summary
...
D: found storage & cache button
D: storage & cache button is enabled
D: perform action click on storage & cache button
`

**Comment by bmx666** [comment]
According quick google answers Samsung Galaxy Tabs have some issue with apps that uses Accessibility Service. Please have a look and test default Google app - [TalkBack](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback)

**Comment by ggsmida0329** [comment]
I downloaded TalkBack, but I'm not sure if it has switched over to Google's version or if it's still using the One UI default because it still doesn't work.

**Comment by bmx666** [comment]
Hi @ggsmida0329 , I will close this issue because it's not fixable.
