### ISSUE TITLE
translate to brazilian portuguese

### ISSUE THREAD

**Issue by JonatasVi** [bmx666/android-appcachecleaner#4]
I would like to contribute to the translation of the application into Brazilian Portuguese

**Comment by bmx666** [comment]
Hi @JonatasVi, thank you! You can make Pull-Request for that.

## For app

All resource strings can be found here ->
https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/main/res/values/strings.xml

Add translated strings for Brazilian Portuguese here ->
https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/main/res/values-pt-rBR/strings.xml

like I did for Russian here as example ->
https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/main/res/values-ru/strings.xml

## For F-Droid / fastline

Short description / short_description.txt ->
https://github.com/bmx666/android-appcachecleaner/blob/main/fastlane/metadata/android/en-US/short_description.txt

Full description / full_description.txt ->
https://github.com/bmx666/android-appcachecleaner/blob/main/fastlane/metadata/android/en-US/full_description.txt

for Brazilian Portuguese is should folder as **pt-BR**
