### ISSUE TITLE
[feature request] save custom set of apps to clean, and create homescreen shortcuts

### ISSUE THREAD

**Issue by e-t-l** [bmx666/android-appcachecleaner#48]
It would be fantastic if there was a way for users to create and save their own set of which apps to clean (i.e. beyond the basic "installed"/"system"/"all"). For example, a user could select a dozen specific apps out of the list and save that as a preset, so in the future those apps could be cleaned in one tap.

Along with this, it would greatly increase usability if this app could put homescreen shortcuts to trigger the cleaning of one of these predefined sets.

**Comment by bmx666** [comment]
Hi @e-t-l 

I will close this issue, please check issue #24 and #30
