### ISSUE TITLE
Allow specifying apps to include/exclude

### ISSUE THREAD

**Issue by Gitoffthelawn** [bmx666/android-appcachecleaner#5]
I just found this repo, and it looks interesting.  I look forward to it being added to F-Droid soon.

Would it be possible to allow the user to specify apps to include/exclude?  IOW, allow the user to specify an "opt-in" or "opt-out" mode for apps to process, and then allow the user to manage exceptions for that made.

Thanks!

**Comment by bmx666** [comment]
Hi @Gitoffthelawn, sorry I didn't get your idea. Do you want to have 2 separated lists: always checked and always unchecked?

I implemented simple checked list for all packages, it will save only checked apps after clicking on "Clean" button and show them next time.

![Screenshot_20220518_204626](https://user-images.githubusercontent.com/2761506/169123164-27625708-d7c5-419d-a3a9-d2f25c01231a.png)

**Comment by bmx666** [comment]
Hi @Gitoffthelawn do you have any feedback or this issue can be closed?
