### ISSUE TITLE
Xiaomi and version 1.1.0 

### ISSUE THREAD

**Issue by franco27** [bmx666/android-appcachecleaner#52]
Hello
 I wish you a happy new year.

 I discovered your app recently.  I just updated to version 1.1.0.
 I found that the cleanup process to clear the app cache has been changed.  You have opted for a new method.

 I am very disappointed because this new method is problematic with my Xiaomi mobile phone.
 Indeed, if I run the cleanup immediately after a restart of the phone or immediately after enabling the accessibility setting, this method works fine.
 If I do the cleaning, at another time, Xiaomi has the annoying tendency to disable accessibility, even though we can see in the settings that it is always enabled.
 I have to force close the app and then re-enable this setting.  (and wait the 10 seconds to be able to do it) or restart the phone.  Which is very annoying.

 I was super happy to have discovered your application which worked perfectly well with the old method (until version 1.0.4).  And now, I end up with the same method as the other applications, similar to your application, that I had tried previously.

 I know what you are going to tell me that for these Xiaomi phones, there are some settings that need to be disabled or enabled to fix the problem.  But it does not work in a prolonged or permanent way.  ..

 I would like to ask you to reinstate the old method for the cleaning process, at least that we can activate it in the settings.  And keep by default, the current method or the new method.

 Sincerely and thanking you in advance.  Thank you for this very good software.

**Comment by bmx666** [comment]
Hi @franco27 

Thanks for feedback, but I left button **Stop Accessibility service** for that case.

**Comment by franco27** [comment]
Thank you for your reply.
 Until version 1.0.4, I used the automatic cleaning process with the accessibility service enabled.
 The accessibility service has been modified.  Before when I went to accessibility settings I saw this (see screenshot) I think it was about accessibility for the visually impaired.

 Since the release of version 1.1.0, and 1.1.1, the accessibility setting is not the same (it is different).  Now, like other apps similar to yours, I have a warning ⚠ with a ten second countdown.  (I have to wait to be able to activate it).  But even after enabling this setting, I still end up with the same issues as others.
 After several hours, depending on Xiaomi, this setting turns off.  Xiaomi tends to close applications in the background and stop accessibility (that of version 1.1.0 and later).

 I explained to you in my first message that accessibility for the visually impaired was better for Xiaomi because I did not encounter any problems.  I really liked the first accessibility system.

**Comment by franco27** [comment]
![Screenshot_2023-01-09-01-08-45-080_com android settings](https://user-images.githubusercontent.com/31793920/211409211-754dc192-fe98-4389-8eac-b8be3a112933.jpg)

**Comment by bmx666** [comment]
@franco27 do you have the same issue with [Click Assistant](https://play.google.com/store/apps/details?id=com.rise.automatic.autoclicker.clicker)?

If yes, sad to hear it, but I don't want to support Accessibility button, because it's not possible to remove it in Android 11 and later, it's always displayed on the screen.

**Comment by bmx666** [comment]
@franco27 in version 1.0.4 - when you press "Close app" - app close self and stop service, in version 1.1.0 - button "stop service" - just stop service, so you need manually remove app from task manager.

**Comment by bmx666** [comment]
@franco27 it still in working progress - Settings menu, I will add option to use button "Close app" or "Stop service". But it requires explanation for other users - why they should use it and maybe shortcuts or widgets can't be used anymore.

**Comment by bmx666** [comment]
Hi @franco27, can you check release v1.1.1 with button "Close app" ? Is it work fine?

Rename from zip to apk and re-install
[app-v1.1.1-close-app.zip](https://github.com/bmx666/android-appcachecleaner/files/10377417/app-v1.1.1-close-app.zip)

**Comment by franco27** [comment]
Yes thanks.
the button works well and is useful. This closes the service and closes the application

**Comment by franco27** [comment]
Until version 104, I didn't get the warning when I enabled the accessibility setting. I would have liked to find this system. But this button, will prevent me from restarting the phone or force closing the application to be able to reactivate this parameter.
Thanks

**Comment by bmx666** [comment]
Hi @franco27, I still didn't get your issue, because you can press "stop accessibility service" and put app into background. Why Xaomi is affected and force to remove app from task manager... Strange.
