### ISSUE TITLE
Presets for different vendors

### ISSUE THREAD

**Issue by notramo** [bmx666/android-appcachecleaner#58]
In order to make it more user friendly, it sould contain presets for the UI text, and autoselect them on certain devices.

**Comment by bmx666** [comment]
Hi @notramo , what do you mean "presets for the UI text"?

**Comment by notramo** [comment]
The UI text that the app is searching in the Android Settings interface.

**Comment by bmx666** [comment]
In version 1.2.1, I made an improvement to get resource strings directly from the Android Settings app to automate the process. But still, even though these strings are standardized by Google for Android, some companies use their custom Android Settings app, I can easily add these specific strings from it, but only if they don't conflict with the original pure Google Android Settings app. The only difficulty is that the user must specify the smartphone model and Android version, in which case Settings.apk can be extracted from Android ROM for analysis.

**Comment by bmx666** [comment]
Please check this commit - https://github.com/bmx666/android-appcachecleaner/commit/827293653d7a8e4f6aae532c27d911b29d16e1ad#

* standard resource string for "Clear cache" button - "clear_cache_btn_text"
* standard resource string for "Storage" menu for Android N (7.1 and early) - "storage_label"
* standard resource string for "Storage" menu for Android O (8.0 and later) - "storage_settings_for_app"

Some companies like Xiaomi and Huawei are still using "storage_label" even on Android 12.
I don't want to implement "Device, smartphone and model" detection only for that. So I put all eggs into one basket...

**Comment by bmx666** [comment]
Hi @notramo do you have anything to suggest something more about the issue or can it be closed?
