### ISSUE TITLE
Help with clear cache for all apps at once

### ISSUE THREAD

**Issue by andreewmat** [bmx666/android-appcachecleaner#82]
Hello, I am trying to delete the cache from all apps at once but I have a problem.
I tried to follow the guide from the description but maybe I do something wrong because every time I select all apps to clear, the process repeat for the first app.

I uploaded below a video with my issue, hope it will help for better understanding. 
https://user-images.githubusercontent.com/79897301/219442873-dd52cb99-671c-48e1-809e-8379e318f9bf.mp4

I am using the latest version from F-Droid and Android 10.

**Comment by bmx666** [comment]
Hi @andreewmat can you test the latest debug version below?

[cache-cleaner-1.5.2-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/10760153/cache-cleaner-1.5.2-debug.zip)

Rename zip into apk and install on your smartphone. It will be an independent app called "Cache Cleaner Debug". Check 2-3 apps and after clean process it generate log-file (it does not contain any sensitive or personal information, only the name and version of apps) and attach it here. I will analyze log-file later.

Also please read issue #8  and in most cases a reboot can help.

**Comment by andreewmat** [comment]
Hello @bmx666, I tested the debug version and there is the [appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/10774998/appcachecleaner-log.txt). Hope it will help.
For reference, I am using Huawei with EMUI 12 with Android 10.

**Comment by bmx666** [comment]
Hi @andreewmat  thanks for the log. There is not an issue from Accessibility Service side.
Can you check one more thing to verify if your Settings doesn't include modification from vendor.
Open "Help" and find button "Open App Info", it should open "App Info" of "Cache Cleaner".
If this does not happen in your case, then you have a modification, and I need to find a solution specific to your phone model...

**Comment by andreewmat** [comment]
Helo @bmx666 I need to open the "Help" buttom from the app, right? If this is the right location, I don't see any "Open App Settings" button.

**Comment by bmx666** [comment]
Hi @andreewmat , sorry my fault, button is displayed only for Android 13 and later.
I made quick modification to display it for all Android versions.

[cache-cleaner-1.5.3-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/10775120/cache-cleaner-1.5.3-debug.zip)

Rename zip into apk and install on your smartphone. Open app and go to "Help" menu top-right corner, find a button "Open App Settings" and click on it.

![Screenshot_20230218_212034](https://user-images.githubusercontent.com/2761506/219893756-08620852-e24b-43f2-8733-b9463fa630d3.png)

![Screenshot_20230218_212235](https://user-images.githubusercontent.com/2761506/219893930-6b527125-efb9-4207-9c3c-4d4109ef0c21.png)

**Comment by andreewmat** [comment]
Hello @bmx666 I just tested the app and it shows me the "App Info" of Clear Cache.

**Comment by bmx666** [comment]
Hi @andreewmat , hmm strange, btw if you select only 3rd apps like "Chrome", "Instagram", "Twitter", "Gmail" and then run cleaning process, does it work ok?
If you exclude Settings from the list, what happens?

**Comment by andreewmat** [comment]
Hello @bmx666 
> Hi @andreewmat , hmm strange, btw if you select only 3rd apps like "Chrome", "Instagram", "Twitter", "Gmail" and then run cleaning process, does it work ok? 

It doesn't work, it is the same as before.

> What happens if you exclude Settings from the list? Maybe when you select "Settings" / "com.android.settings" it has some side effect in EMUI?

How can I exclude it? I should delete the cache on "Settings" app?

**Comment by bmx666** [comment]
> It doesn't work, it is the same as before.
Even when you just check only one "Gmail"? There is no differenect - when you click "Open App Settings" or it open apps from list. The code is the same.

> How can I exclude it? I should delete the cache on "Settings" app?
No, just don't check it.

**Comment by andreewmat** [comment]
Hello @bmx666 
> Even when you just check only one "Gmail"? 

When I select only one app it works ok.

> No, just don't check it.

I tried to select all system app and exclude settings and still the same.

**Comment by bmx666** [comment]
@andreewmat so if you select 3rd party apps like Gmail, Chrome and etc. (NOT SYSTEM APPS) then Cache Cleaner works fine? If yes then check forums about your smartphone, EMUI and other Android customized stuff and why some system apps is redirecting to Settings, because it has 0 relation to Cache Cleaner and I don't want to put a lot of effort to create a fix for one specific smartphone, only if someone will be interesting in it. Otherwise if 3rd party apps are not cleaning at all then reopen this issue.

**Comment by andreewmat** [comment]
@bmx666 I tried to select user apps but it's the same issue as system apps. As the video posted above, after I select some user apps and press clear button it bootloop into the first app that try to clean.

**Comment by bmx666** [comment]
Hi @andreewmat can you test the latest debug version below? I added logs to check which package names are used to open AppInfo.

[cache-cleaner-1.5.3-debug-v3.zip](https://github.com/bmx666/android-appcachecleaner/files/10777002/cache-cleaner-1.5.3-debug-v3.zip)

Rename zip into apk and install on your smartphone. It will be an independent app called "Cache Cleaner Debug". Check 2-3 apps and after clean process it generate log-file (it does not contain any sensitive or personal information, only the name and version of apps) and attach it here. I will analyze log-file later.

**Comment by bmx666** [comment]
Hi @andreewmat , can you test the latest debug version below?

[cache-cleaner-1.5.3-debug-v4.zip](https://github.com/bmx666/android-appcachecleaner/files/10777051/cache-cleaner-1.5.3-debug-v4.zip)

**Comment by andreewmat** [comment]
Hello @bmx666 here is the [appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/10777163/appcachecleaner-log.txt) for the V4 version.

**Comment by bmx666** [comment]
Hi @andreewmat thanks! Cache Cleaner sends different apps (package names) to open AppInfo, but Settings app on your smartphone still return the first one. I'm not sure how fix this issue.

**Comment by YGOmod** [comment]
Hi..I'm having same problem as @andreewmat on my Samsung s22 but maybe I can offer solution.. I'm not programmer or anything but I was testing this app and macrodroid script to clean cache.. I noticed when app/script opens app info, and it doesn't find string (storage or clear cache) in first place it just skips and proceed to next app, for same step.. when it finds it, it opens and clear cache.. so i just added extra step in macrodroid script that it scroll lil bit down until string Storage is visible and it worked.. that moment I got 3GB free space xD.. I don't know how it's with other phones but on my phone Storage is not visible for 99% of apps when you open App Info.. I need to scroll down to see it.. if you could implement similar step in your app, maybe it would solve you troubles.. like open AppInfo, search for string, if not find, scroll and search again and then proceed
Thanks for the app.. keep up with good work 👍🏻

**Comment by YGOmod** [comment]
hey @bmx666.. sorry cuz I haven't seen post about same thing.. here I'm sending you some screenshots and video.. 
![Screenshot_20230410_230421_Settings](https://user-images.githubusercontent.com/130164085/231008019-3d2ee40e-5a50-497b-b6ef-f10e90988a67.jpg)
![Screenshot_20230410_230451_Settings](https://user-images.githubusercontent.com/130164085/231008022-cce8b15c-ba3a-4ea4-89e1-6cf9dffcc7d4.jpg)
![Screenshot_20230410_230541_Settings](https://user-images.githubusercontent.com/130164085/231008024-2b96f639-edbb-4137-ad6c-ae6c68d6777c.jpg)
![Screenshot_20230410_230655_Settings](https://user-images.githubusercontent.com/130164085/231008027-eaaba727-0a39-4542-bd5f-e4dc8439f8e2.jpg)
![Screenshot_20230410_230709_Settings](https://user-images.githubusercontent.com/130164085/231008030-20bd971c-ab45-4a59-91c1-e7c87a0c4173.jpg)
![Screenshot_20230410_230605_Settings](https://user-images.githubusercontent.com/130164085/231008031-ba2d5b29-c3b3-4abe-9a16-bf8d9364c157.jpg)
![Screenshot_20230411_000147_Settings](https://user-images.githubusercontent.com/130164085/231008592-b25c6594-c116-4c8d-8a3a-755aea8b0971.jpg)
![Screenshot_20230411_000123_Settings](https://user-images.githubusercontent.com/130164085/231008594-3cb332e7-46f4-4e2a-88c6-73f785e23be2.jpg)
and here's log file 
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/11194337/appcachecleaner-log.1.txt) 

I have chosen Brave and Discord, which are not showing "storage" in Appinfo, and Clean Cache and Photo Editor which show "storage".. those one who don't show Storage are not cleaned, and other two are cleaned. 

Thanks
