### ISSUE TITLE
UI improvement & speed

### ISSUE THREAD

**Issue by NR8124** [bmx666/android-appcachecleaner#9]
For me the cache somehow started working...
I need that UI to fixed and reframed in better manner
Along with that. Do some work on app's speed

**Comment by bmx666** [comment]
hi @NR8124 I made few UX and UI improvements, improve performance to cache icon and label of installed apps on first scan.

New release [v0.0.8](https://github.com/bmx666/android-appcachecleaner/releases/download/v0.0.8/app-release.apk)

**Comment by NR8124** [comment]
*add menu to add extra search text for storage and clear cache*

When  tapped on this option all the text were not  properly visible in dark mode

**Comment by bmx666** [comment]
Thanks for feedback, never tested in Dark mode. I will check it.

**Comment by NR8124** [comment]
hey @bmx666, can u help me to make a CI in this repository i.e. debug apk in actions tab

**Comment by bmx666** [comment]
Hi @NR8124 , check new release [v0.0.9](https://github.com/bmx666/android-appcachecleaner/releases/download/v0.0.9/app-release.apk)

**Comment by bmx666** [comment]
Hi @NR8124 , check new release [v0.1.1](https://github.com/bmx666/android-appcachecleaner/releases/download/v0.1.1/app-release.apk)

I can improve speed a little bit more, if dynamically check "cache size of each app", but then UI constantly will be updated and re-sort package list in descending order, to show app with bigger cache size at the top. Or as option - force disable to check app cache size during list generation, like in Android 7.1 and early... where that feature is not working.

Anyway, if you happy with speed, you can close this issue.

P.S. In final release 1.0.0 I have plans to add help menu and think about welcome screen for non-advanced users.

**Comment by NR8124** [comment]
@bmx666 Thanx for the considering the issue and showing ur efforts towards it ❤
for me the speed is very good and your app is working very fine now 🙌
