### ISSUE TITLE
Doesn't work on Samsung Galaxy devices.

### ISSUE THREAD

**Issue by Onako2** [bmx666/android-appcachecleaner#93]
As I saw the App detects some apps but not all apps where the cache clean button is and the memory or how it's called.
How it could be fixed: If the app doesn't detect a button it scrolls down to see the button. (Apps which didn't have much scrolling have been detected)

**Comment by bmx666** [comment]
Hi @Onako2 could you please provide video?

Android Accessibility Service send back all Node View tree of elements, and "Cache Cleaner" can do perform click on button, even it our of physical view.

Can you also attach log file from debug version?

[cache-cleaner-1.5.3-debug-v4.zip](https://github.com/bmx666/android-appcachecleaner/files/10777051/cache-cleaner-1.5.3-debug-v4.zip)

Rename zip into apk and install on your smartphone. It will be an independent app called "Cache Cleaner Debug". Check 2-3 "problematic" apps and after clean process it generate log-file (it does not contain any sensitive or personal information, only the name and version of apps) and attach it here. I will analyze log-file later.

**Comment by bmx666** [comment]
Hi @Onako2, I will close this issue due to inactivity.

**Comment by bmx666** [comment]
@YGOmod thanks a lot for feedback, I moved conversation in that issue, because previous was about something different

https://github.com/bmx666/android-appcachecleaner/issues/82#issuecomment-1502395171

And thank you very much for your feedback, it's really helpful. Now I see the problem why it wasn't showing because it uses RecycleView where the items are created dynamically. But I don't understand why Samsung uses this type because there is no performance gain.

**Comment by YGOmod** [comment]
no problem.. if you need more feedback, let me know.. I hope you will manage to fix it coz this is the only software that literally works and clear cache 😁👍🏻

**Comment by bmx666** [comment]
Hi @YGOmod  I found how to reproduce this problem on emulators if I set huge text size and huge display size. I hope new release - [v1.6.0](https://github.com/bmx666/android-appcachecleaner/releases/tag/v1.6.0) will work in your case too. If not, then feel free to re-open this issue again.

**Comment by YGOmod** [comment]
thanks, it works perfect now 😁👍🏻

**Comment by bmx666** [comment]
@YGOmod  you can use F-Droid app manager to get new updates.
