### ISSUE TITLE
Android 7.0, cache-size is not shown

### ISSUE THREAD

**Issue by RichardBeisser** [bmx666/android-appcachecleaner#95]
Hello,

on an Android 7.0 device, the app doesnt show in the lists off apps the cache size of apps.
When finished, the app also doesnt show how much storage could be freed.

Anything you can do here?

Thanks.

**Comment by bmx666** [comment]
Hi @RichardBeisser, yes because StorageStats API to get storage info about app was implemented in Android 8.0
