### ISSUE TITLE
Apps doesnt clean / could not clean cache on all apps

### ISSUE THREAD

**Issue by RichardBeisser** [bmx666/android-appcachecleaner#96]
Hello,

I notice several times (devices with Android 10 + 12) that the apps through all selected apps. When I click again clean user apps, there are still apps which have the same cache size.
When I go into app-manager of android and have a look on cache usage, here is also shown that the has not cleaned the cache.

When I start a second run, in most cases, the app could clean cache.

Anything you can do here?

Thanks.

**Comment by bmx666** [comment]
Hi @RichardBeisser , please read my comment - https://github.com/bmx666/android-appcachecleaner/issues/87#issuecomment-1440296542
